### ISSUE TITLE
Show case

### ISSUE THREAD

**Issue by kevinhwang91** [kevinhwang91/rnvimr#1]
![demo](https://user-images.githubusercontent.com/17562139/74416173-b0aa8600-4e7f-11ea-83b5-31c07c384af1.gif)

**Comment by kevinhwang91** [comment]
![sync pager](https://user-images.githubusercontent.com/17562139/79063322-8a646380-7cd3-11ea-9184-189b134b5eef.gif)

**Comment by kevinhwang91** [comment]
![better pager view](https://user-images.githubusercontent.com/17562139/79363617-b5241580-7f7a-11ea-9332-bd865dd2cf1e.gif)

**Comment by miko2009** [comment]
请问一下，我在vim里面安装了插件。但是快捷键ctr+t 和ctrl + x 没有效果。请问一下是什么原因。ranger 我没有修改键位。

**Comment by kevinhwang91** [comment]
> 请问一下，我在vim里面安装了插件。但是快捷键ctr+t 和ctrl + x 没有效果。请问一下是什么原因。ranger 我没有修改键位。

不支持vim。如果是neovim，请确保你的快捷键没有覆盖imap的ctrl+t/x。如果有进一步问题需要探讨，请开issue。觉得写英文麻烦可以用google机翻译，方便其他外国人查看issue。

**Comment by miko2009** [comment]
thank you for your help  i had solve the problem

**Comment by kevinhwang91** [comment]
Don't comment on this issue, please.

**Comment by kevinhwang91** [comment]
![hide gitignore](https://user-images.githubusercontent.com/17562139/86021661-ec737000-ba5b-11ea-9717-f7c124b42558.png)

**Comment by kevinhwang91** [comment]
![hide gitignore](https://user-images.githubusercontent.com/17562139/86022414-ea5de100-ba5c-11ea-9e49-ff9ec095d720.png)

**Comment by kevinhwang91** [comment]
![save-buffer-info](https://user-images.githubusercontent.com/17562139/86033825-23518200-ba6c-11ea-88d6-914d8d8f1f96.gif)

**Comment by kevinhwang91** [comment]
![hide-gitignore](https://user-images.githubusercontent.com/17562139/86036499-8e04bc80-ba70-11ea-9f89-dac26795b7ec.png)

**Comment by kevinhwang91** [comment]
![demo](https://user-images.githubusercontent.com/17562139/94383438-a3be7680-0172-11eb-9f57-f3cd88aff0c0.gif)
