### ISSUE TITLE
Unable to quit ranger, not updating dir on opening a directory

### ISSUE THREAD

**Issue by JosefLitos** [kevinhwang91/rnvimr#100]
- `nvim --version`:
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
přeložil  builduser

Features: +acl +iconv +tui
```
- Operating system/version: Archlinux 1.0
- `nvim +'checkhealth rnvimr'`: 
```

rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - OK: Ueberzug is ready

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"

```
**Describe the bug**
rnvimr doesn't update to current file after being launcher for the first time

1. literally, open with it a file
2. go elsewhere - like dir, or just select some file
3. open ranger again

**Expected behavior**
open at the currently viewed file
**Screenshots**

**Additional context**
This bug started happening after an update on 2. or 3.1.2022

**Comment by kevinhwang91** [comment]
Thanks, fixed now.
