### ISSUE TITLE
can it open all selected files at once while some selected files are located in different directories?

### ISSUE THREAD

**Issue by wizenith** [kevinhwang91/rnvimr#105]
Thanks for creating this great plugin, I am enjoy finding files by having the ranger integrated with nvim, but I did encounter a problem that it only opened the files I selected in the current directory, but not with other files where are from other folders. Please kindly advise if there is any way to achieve it. Thank you.

**Comment by kevinhwang91** [comment]
But this is the ranger default behavior.

**Comment by wizenith** [comment]
Oh I get it, I thought it might be able to save the selection items as a array and open those buffer files from the array, thank you for quick reply. I will close this issue then.
