### ISSUE TITLE
How do I show hidden files by default?

### ISSUE THREAD

**Issue by kantord** [kevinhwang91/rnvimr#107]
**Is your feature request related to a problem? Please describe.**

I have the following in my rc.conf

```
set show_hidden true
```

and in vanilla ranger, I can see hidden files by default. However, in this plugin, I can't see hidden files by default. I don't necessarily want to enable "vanilla mode" in this plugin, but I can't find any other way based on the documentation to show hidden files by default.

**Describe the solution you'd like**
I would like to have an option that I can set in order to show hidden files by default

**Describe alternatives you've considered**
I considered creating a separate configuration using `g:rnvimr_urc_path` but I'm not sure if this is a future proof idea. It means that if the default configurations in this plugin change with an update, I won't receive that update when I update the plugin, no? Also, I need to copy the current default configuration into this new config file, no?

Another alternative I can imagine is to provide the option to somehow merge 2 config files. So similar to `g:rnvimr_vanilla` but it should be an option that merges the default settings defined by this plugin with the user settings defined in a file or the global ranger config.

**Comment by kevinhwang91** [comment]
can't reproduce, try minimal config.

**Comment by kantord** [comment]
I can't reproduce it anymore either
