### ISSUE TITLE
E117: Unknown function: stdpath

### ISSUE THREAD

**Issue by xuta** [kevinhwang91/rnvimr#11]
```vim
Error detected while processing function <SNR>13_LoadRemotePlugins[1]..<SNR>13_GetManifest[1]..<SNR>13_GetManifestPath:7:
E117: Unknown function: stdpath
E15: Invalid expression: stdpath('data')
Press ENTER or type command to continue
```

It happens when I try to open a file from floating windows by `l` or `Enter`.

Btw, C-T works well.

**Comment by kevinhwang91** [comment]
It seems that the issue caused by your neovim itself, what the message output via invoking `echo stdpath('data')` in neovim?

**Comment by xuta** [comment]
Inside the floating window, it shows

```bash
E117: Unknown function: stdpath
E15: Invalid expression: stdpath('data')
```

and in the main nvim window, it shows

```bash
/User/xuta/.local/share/nvim
```

**Comment by kevinhwang91** [comment]
What's your OS?  `/User/xuta/.local/share/nvim` is likely a Windows's path.
Ranger is not supported Windows.

**Comment by xuta** [comment]
No, it's a macOS, not Windows, sorry for the typo, should be `/Users/`, not `/User/`

```bash
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

**Comment by kevinhwang91** [comment]
Are you still using rnvimr? Have you found a solution or have you replaced rnvimr with another plugin? I kindly ask for your feedback.

**Comment by xuta** [comment]
Hi @kevinhwang91,
I moved to https://github.com/francoiscabrol/ranger.vim, it fits for what I need.
Thanks,

**Comment by alechp** [comment]
@kevinhwang91 I ran into the same issue (stack: Mac, iTerm, Neovim, ranger, rnvimr). 

* Detailed issue (where I got the same error as @xuta )
> https://github.com/ChristianChiarulli/nvim/issues/27

* PDF of some logs re: commands you posted
> [neovim & ranger.pdf](https://github.com/kevinhwang91/rnvimr/files/4783683/neovim.ranger.pdf)

In the meantime, moved to ranger.vim. I would prefer to use rnvimr. Any suggestions on debugging?

**Comment by kevinhwang91** [comment]
What's the msg does `nvim +'checkhealth rnvimr` say? 

It works fine for My mac.

I install `neovim` by `brew` and install `ranger` and  `pynvim` by `pip3`. Please refer https://github.com/kevinhwang91/rnvimr#Installation.

**Comment by alechp** [comment]
> I install `neovim` by `brew` and install `ranger` and `pynvim` by `pip3`. Please refer [kevinhwang91/rnvimr#Installation](https://github.com/kevinhwang91/rnvimr#Installation).

Thank you @kevinhwang91 
That helped me figure out my problem; I installed the wrong dependency

<img width="341" alt="Screen Shot 2020-06-16 at 12 42 12 PM" src="https://user-images.githubusercontent.com/3058939/84820719-e9de3880-afce-11ea-9665-fd5852d6cadb.png">


<img width="313" alt="Screen Shot 2020-06-16 at 12 42 08 PM" src="https://user-images.githubusercontent.com/3058939/84820718-e8ad0b80-afce-11ea-856b-39eec25d5ce3.png">
