### ISSUE TITLE
Opening files causes errors inside floating terminal. 

### ISSUE THREAD

**Issue by prdanelli** [kevinhwang91/rnvimr#111]
Firstly, I just wanted to say that your plugin is absolutely the best file navigation plugin i've used for Vim or Nvim, I used it every day when I was on linux and it was honestly amazing. I moved to MacOS and it seems to have issues around opening files, which is a huge bummer because no other file navigation plugin closed anywhere near as close to how nice RnVimr is to use. 

I really hope this bug report helps to narrow down what might be causing the issue, because i'd love to be able to use it again. 

- `nvim --version`:
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

- Operating system/version: 
`macOS 12.3.1 21E258 arm64`

- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.12 (main, Mar 26 2022, 15:44:31) [Clang 13.1.6 (clang-1316.0.21.2)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```

**Describe the bug**

When I try to open a file using Rnvimr, I see the following error messages, pressing `q` then opens the file inside of the floating terminal and requires `:q` to close the terminal: 

```Invalid linemode: devicons2; should be filename/metatitle/permissions/filei
nfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemtime
E1187: Failed to source defaults.vim
Error detected while processing /opt/homebrew/Cellar/neovim/0.7.0/share/nvim
/runtime/plugin/man.vim:
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
Error detected while processing /opt/homebrew/Cellar/neovim/0.7.0/share/nvim
/runtime/plugin/rplugin.vim[65]..function <SNR>10_LoadRemotePlugins[1]..<SNR
>10_GetManifest[1]..<SNR>10_GetManifestPath:
line    7:
E117: Unknown function: stdpath
--- Autocommands ---
Error detected while processing /opt/homebrew/Cellar/neovim/0.7.0/share/nvim
/runtime/plugin/shada.vim:
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   16:
E10: \ should be followed by /, ? or &
line   17:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
line   20:
E35: No previous regular expression
line   21:
E10: \ should be followed by /, ? or &
line   22:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   24:
E10: \ should be followed by /, ? or &
line   25:
E10: \ should be followed by /, ? or &
line   26:
E10: \ should be followed by /, ? or &
line   27:
E10: \ should be followed by /, ? or &
line   28:
E10: \ should be followed by /, ? or &
line   29:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   31:
E10: \ should be followed by /, ? or &
line   32:
E10: \ should be followed by /, ? or &
line   33:
E10: \ should be followed by /, ? or &
line   34:
E10: \ should be followed by /, ? or &
line   35:
E10: \ should be followed by /, ? or &
line   36:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   38:
E10: \ should be followed by /, ? or &
Press ENTER or type command to continue
```

**To Reproduce using `nvim -u mini.vim`**

Example:

This is a minimal `init.lua` file that was able to replicate the issue: 

`$ cat nvim/init.lua`

```lua
local fn = vim.fn

-- Automatically install packer
local install_path = fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
        PACKER_BOOTSTRAP = fn.system { "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path }
        print "Installing packer close and reopen Neovim..."
        vim.cmd [[packadd packer.nvim]]
end

-- Use a protected call so we don"t error out on first use
local status_ok, packer = pcall(require, "packer")
if not status_ok then
        return
end

return packer.startup(function(use)
        -- Make packer manage itself
        use "wbthomason/packer.nvim"
        use "kevinhwang91/rnvimr"

        -----------------------------------------------------------------------------
        -- Automatically set up your configuration after cloning packer.nvim
        -- Put this at the end after all plugins
        -----------------------------------------------------------------------------
        if PACKER_BOOTSTRAP then
                require("packer").sync()
        end
end)

```

1. run `:RnvimrToggle`
2. Try to open a file

**Expected behavior**
File should be opened in Nvim and the floating terminal closed

**Screenshots**

`:RnvimrToggle`
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1199977/165843759-19e75f9f-f326-4c86-b696-eb5d50450310.png">

Opened `init.lua`: 
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/1199977/165843786-2a4ebf92-f9ae-4ec2-baa5-f3ddfcb0a1c4.png">

Pressed Enter: 
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1199977/165843827-1ec09b59-be76-4219-8645-8788926e9218.png">

Pressed `:q` 
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1199977/165843948-2a491a66-46e2-4b6e-93de-77c0bec628eb.png">

`q` then closes the floating terminal

**Additional context**

**Comment by kevinhwang91** [comment]
Does this works for you? https://github.com/kevinhwang91/rnvimr/issues/11

**Comment by prdanelli** [comment]
@kevinhwang91 Thank you for replying so quickly. 

For `echo stdpath('data')`, I get `/Users/paul/.local/share/nvim`. 

I had installed ranger via `pip3 install ranger-fm` as suggested in the install guide. 

```ranger --version 

ranger version: ranger 1.9.3
Python version: 3.9.12 (main, Mar 26 2022, 15:44:31) [Clang 13.1.6 (clang-1316.0.21.2)]
Locale: en_GB.UTF-8```

But the issue still persists. :(

**Comment by kevinhwang91** [comment]
I can't reproduce the issue.
Please try `nvim -u NONE -i NONE mini.lua +'so'`, and open a file.
`cat mini.lua`
```lua
vim.cmd('pa rnvimr')
vim.defer_fn(function()
    vim.cmd('RnvimrToggle')
end, 100)
```

**Comment by prdanelli** [comment]
@kevinhwang91 I created the `mini.lua` file wit the content you suggested. 

When the file is executed by Nvim, Rnvimr opens on load: 

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1199977/166001985-6e4ab541-d8f9-44ac-a32f-deda83ea74a9.png">

When I try and open a file, I get the following: 

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/1199977/166002113-4cd6d17e-38e9-48fd-ac57-b7dab7a7e42a.png">

The error seems to the same as before, however I cannot copy it because mouse interactions are disabled and any keypress closes the dialogue.

When I hit enter, the file is then opened within the terminal in what looks like an instance of Nvim. 

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/1199977/166002907-4667f795-24f6-4c94-b7bf-42ac195b9a1f.png">

**Comment by kevinhwang91** [comment]
How about execute `eval fm.client.rpc_edit(['mini.lua'])` in *Ranger* command mode?

**Comment by prdanelli** [comment]
So, that seems to open the file: 

From an empty buffer: 
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/1199977/166006728-c9fd9924-75dc-45ac-b187-2ddb777ad74f.png">

Inside the command mode: 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1199977/166006780-1f369c2d-ae29-482d-949f-cbb1058abf9f.png">

Hit enter and the file is opened with the terminal window still open: 
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1199977/166006823-c40535dc-51ee-4c3c-9ce9-e965ccad1781.png">

**Comment by kevinhwang91** [comment]
But the buffer has been changed to `mini.lua` right?

**Comment by prdanelli** [comment]
That is correct. I closed mini.lua buffer initially to make it clear that the command you provided opened the file inside of the normal Nvim window, without causing the error. 

Using the following, also opened the file inside a normal Nvim buffer without error: 

`eval fm.client.rpc_edit(['init.lua'])`

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/1199977/166007987-2e34e41d-f827-4309-802f-58bfe395a660.png">

**Comment by kevinhwang91** [comment]
update the `mini.lua` please, look like it's caused by your Ranger setup.
```lua
vim.cmd('pa rnvimr')
vim.g.rnvimr_vanilla = 1
vim.defer_fn(function()
    vim.cmd('RnvimrToggle')
end, 100)
```

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/rnvimr#faq

**Comment by prdanelli** [comment]
> You can also try `eval fm.client.rpc_edit(['mini.lua'], 'edit')`
> 
> update the `mini.lua` please, look like it's caused by your Ranger setup.
> 
> ```lua
> vim.cmd('pa rnvimr')
> vim.g.rnvimr_vanilla = 1
> vim.defer_fn(function()
>     vim.cmd('RnvimrToggle')
> end, 100)
> ```

I copied the commands into the `mini.lua` and they executed as the previous ones did, opening the file into a buffer whilst the terminal window stays open.

**Comment by prdanelli** [comment]
> https://github.com/kevinhwang91/rnvimr#faq

I did follow that section of the FAQs and couldn't see any issues. 

Pressing `r` inside of Rnvimr, gives me the following: 

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1199977/166009790-2a9f3e65-f53c-4f43-873b-4bb1a1420a67.png">

**Comment by kevinhwang91** [comment]
> > You can also try `eval fm.client.rpc_edit(['mini.lua'], 'edit')`
> > update the `mini.lua` please, look like it's caused by your Ranger setup.
> > ```lua
> > vim.cmd('pa rnvimr')
> > vim.g.rnvimr_vanilla = 1
> > vim.defer_fn(function()
> >     vim.cmd('RnvimrToggle')
> > end, 100)
> > ```
> 
> I copied the commands into the `mini.lua` and they executed as the previous ones did, opening the file into a buffer whilst the terminal window stays open.

`vim.g.rnvimr_vanilla = 1` means skip your Ranger config, you should check out your Ranger config.

**Comment by prdanelli** [comment]
@kevinhwang91 Im so sorry for wasting your time. I'm not exactly sure what it is in my rifle.conf or rc.conf, but removing both files allows the files to be opened normally again. 

Thank you for your time and thank you again for making such a useful plugin.

**Comment by kevinhwang91** [comment]
Never mind
