### ISSUE TITLE
用alt+O 快捷键打开一直如下错误

### ISSUE THREAD

**Issue by 505384662** [kevinhwang91/rnvimr#116]
![image](https://user-images.githubusercontent.com/31720616/168544812-db3f5cbc-3219-40fc-946f-aec3eaf616a7.png)

**Comment by kevinhwang91** [comment]
minimal config.

**Comment by 505384662** [comment]
I don't quite understand what you mean。

**Comment by kevinhwang91** [comment]
issue template:

```markdown
<!-- Before reporting: search existing issues and check the FAQ. -->

- `nvim --version`:
- Operating system/version:
- `nvim +'checkhealth rnvimr'`: 
```
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_vanilla = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

Steps to reproduce the behavior:
1.
2.
3.
```

**Comment by 505384662** [comment]
this is my  checkhealth rnvim
![image](https://user-images.githubusercontent.com/31720616/168565586-0209333c-230f-4d82-addf-8b90aacc996c.png)
this is my ranger version
![image](https://user-images.githubusercontent.com/31720616/168565661-4033c669-f73a-4c5d-9e81-b1bcf8b41dcc.png)
this is my neovim version 
![image](https://user-images.githubusercontent.com/31720616/168565880-edccbe0a-bd76-4a90-9f7e-c78a82ec2acc.png)
this is my init.vim config
![image](https://user-images.githubusercontent.com/31720616/168566754-e465c301-0981-4c89-9e8b-d0847cd4cef9.png)
![image](https://user-images.githubusercontent.com/31720616/168566847-7f719dba-7328-4f7c-8f65-01392b27f277.png)
![image](https://user-images.githubusercontent.com/31720616/168566906-65d57c38-85f9-4b82-84d9-b61aaf471cde.png)


my steps ~
1 nvim
2 alt + o 
 coming after：
![image](https://user-images.githubusercontent.com/31720616/168566368-69e70c9f-43a8-4768-a3e0-0dcfa5813256.png)

Thank you very much
Good job!

**Comment by kevinhwang91** [comment]
Have reproduced. Caused by https://github.com/kevinhwang91/rnvimr/commit/d2d3b7014eeeedec027fe844e3b9c68e169fb169

**Comment by kevinhwang91** [comment]
Please update the code and your config to:
```vim
let g:rnvimr_ranger_cmd = ['ranger', '--cmd=set draw_borders both']
```

**Comment by 505384662** [comment]
OK  wait a second  I'm just do it

**Comment by 505384662** [comment]
it's ok now ~ 3q

**Comment by laggardkernel** [comment]
> Please update the code and your config to:
> 
> ```viml
> let g:rnvimr_ranger_cmd = ['ranger', '--cmd=set draw_borders both']
> ```

I don't get it. The list is not split by space, but by `ranger` command and its arguments?

**Comment by kevinhwang91** [comment]
> > Please update the code and your config to:
> > ```viml
> > let g:rnvimr_ranger_cmd = ['ranger', '--cmd=set draw_borders both']
> > ```
> 
> I don't get it. The list is not split by space, but by `ranger` command and its arguments?

`h termopen()`, `g:rnvimr_ranger_cmd` will be passed into `{cmd}`
