### ISSUE TITLE
Ranger can't open newly-created / empty files

### ISSUE THREAD

**Issue by kgreenek** [kevinhwang91/rnvimr#119]
- `nvim --version`: v0.8.0-dev
- Operating system/version: Ubuntu 22.04
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - WARNING: Ueberzug is not found in Python Lib

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
If I create a new empty file, I cannot open it from the ranger view. When I try to open it in the ranger window, nothing happens. It appears to flicker for a second, but then does not open the file. The ranger window remains open.

**To Reproduce using `nvim -u mini.vim`**

**Expected behavior**
Empty files should just open like normal.

**Comment by kevinhwang91** [comment]
Read the FAQ and follow the mini config before opening the issue.
