### ISSUE TITLE
RPC Timeout

### ISSUE THREAD

**Issue by Stianhn** [kevinhwang91/rnvimr#120]
- `nvim --version`: 0.7.0
- Operating system/version: MacOS 12.4
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - ERROR: RPC: timeout 3s

```
**Describe the bug**

- The borders are not being drawn.
- When opening ranger for the first time it gives me this error `Command not found Attach file`.
- Opening a file opens it inside of the modal.
- Navigating the files is a bit laggy.

I'm setting the option `rnvimr_vanilla = 1`. 
`echo $NVIM_LISTEN_ADDRESS` returns `/var/folders/....`

Is there any more information I can provide to simplify the debugging?

**Comment by kevinhwang91** [comment]
Look like pynvim can't be imported under ranger.

Open ranger outside nvim, and then run `:eval import pynvim; fm.notify(pynvim)`

**Comment by Stianhn** [comment]
Looks like your assumption was right. Any idea why nvim can find pynvim but not ranger?

**Comment by kevinhwang91** [comment]
```log
## Pynvim
  - OK: Version: 0.4.3
``` 
in checkhealth is your system python ENV. 
`python3 -c "import pynvim; v = pynvim.VERSION; print(v.major, v.minor, v.patch, sep=\".\", end=\"\")"`

Your ranger installation path is not the same as your system python.

**Comment by Stianhn** [comment]
Thanks for the help @kevinhwang91 ❤️ I think I must have insntalled the wrong ranger version. After I installed the ranger-fm version the healthcheck passed 👍
