### ISSUE TITLE
The preview text in light themes is unreadable

### ISSUE THREAD

**Issue by Jeaciaz** [kevinhwang91/rnvimr#121]
- `nvim --version`: v0.7.0
- Operating system/version: macOS Catalina 10.15.7
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.13 (main, May 24 2022, 21:28:12) [Clang 12.0.0 (clang-1200.0.32.29)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
On a light theme, the text file preview colors are not adjusted, which results in white text which is very painful to read. I couldn't find the corresponding :hl group, neither am I sure there is one.

**To Reproduce using `nvim -u mini.vim`**
Example:
`cat mini.vim`
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
Plug 'ellisonleao/gruvbox.nvim'
colorscheme gruvbox
set background=light
let g:rnvimr_vanilla = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

1. Create a .txt file with any contents;
2. Open Neovim with `mini.vim` provided above;
3. Hover over the .txt file from 1.;
4. See that all text is white and undiscernable.

**Expected behavior**
A clear to read text using whatever theme the user prefers.

**Screenshots**
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/6773331/180606639-8edd269b-6ba2-4df5-9815-15da7930a363.png">
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/6773331/180606651-0fe18606-9c9f-4544-b1d0-c5f60d87d3f1.png">

**Additional context**

**Comment by kevinhwang91** [comment]
Depend on your previewer theme in ranger.

**Comment by Jeaciaz** [comment]
But in my terminal it's all right, although colorless. Where does the color difference come from?

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/rnvimr/issues/67
