### ISSUE TITLE
C-v triggers only after pressing it two times

### ISSUE THREAD

**Issue by divramod** [kevinhwang91/rnvimr#122]
- `nvim --version`: 0.7.2
- Operating system/version: macos Darwin mod 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```

**Describe the bug**
- i mapped C-v to NvimEdit vsplit (see my example)
- i need to press c-v two times to take effect
- running shortcut ev opens the vsplit at the first try (see my example)
- i tried it with vanilla and with my own ranger config
- i tried it in iterm2 and in the default osx editor
- i tried it with zsh, bash and zsh

**To Reproduce using `nvim -u mini.vim`**

my Example:
`cat mini.vim`
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_vanilla = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <C-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
let g:rnvimr_vanilla = 1

let g:rnvimr_action = {
\ '<Enter>': 'NvimEdit edit',
\ '<C-t>': 'NvimEdit tabedit',
\ '<C-x>': 'NvimEdit split',
\ '<C-v>': 'NvimEdit vsplit',
\ 'ev': 'NvimEdit vsplit',
\ 'eh': 'NvimEdit split',
\ 'et': 'NvimEdit tabedit',
\ 'ee': 'NvimEdit edit',
\ 'gw': 'JumpNvimCwd',
\ 'yw': 'EmitRangerCwd'
\ }
```

**Expected behavior**
- NvimEdit vsplit will be triggered at the first time when pressing C-v

**Comment by kevinhwang91** [comment]
>Q: In MacOS, I must press <ctrl-v> twice to split window vertically.

>A: Please refer to https://github.com/kevinhwang91/rnvimr/issues/71 and use rnvimr_action variable to remap <ctrl-v> as a workaround for the issue.

**Comment by divramod** [comment]
i'm sorry. rtfm. https://github.com/kevinhwang91/rnvimr/issues/71#issuecomment-1072923677 fixed it for me
thx for your fast reply and the awesome plugin!
