### ISSUE TITLE
Magenta background

### ISSUE THREAD

**Issue by Mirkopoj** [kevinhwang91/rnvimr#126]
- `nvim --version`: v0.8.0
- Operating system/version: Arch Linux, Kernel: 5.19.12 
- `nvim +'checkhealth rnvimr'`: 
```
OS - OK
Ranger - OK: Version: ranger 1.9.3
Python - OK: Version 3.10.7
Pynvim - OK: Version 0.4.3
Ueberzug - OK
RPC - OK
```
**Describe the bug**
The popup window has a magenta color that makes some text unreadable, since I updated nvim, it used to be fine.

My config file:

```vim


" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr', {'do':  'make sync'}
call plug#end()
let g:rnvimr_ex_enable = 1
nmap <space>r :RnvimrToggle<CR>

```

**Expected behavior**
Getting the same window as standalone ranger, this used to be the case.

**Screenshots**
How it looks now
![RangerPlugin](https://user-images.githubusercontent.com/74278752/193436058-559dd9cf-bf00-4f6a-8a6c-5bd560132408.png)
How ranger looks, and how it used to look, prior to nvim v0.8.0
![Ranger](https://user-images.githubusercontent.com/74278752/193436086-cb2d377f-8193-4626-aa57-99ec5dc78250.png)

**Comment by kevinhwang91** [comment]
can't reproduce it, please use a min config.

**Comment by Mirkopoj** [comment]
I'm sorry if I miss understood, I tried using this as my config file with no luck.

```
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_vanilla = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```
I had the same issue on an ubuntu machine at an office, running an older veersion of nvim, tomorrow I'll be able to check which. I'm guessing the problem may be in my QTile config, as thats the main thing this two PCs have in common.

![RangerPluginMinConf](https://user-images.githubusercontent.com/74278752/193474044-29f809d3-400e-48ba-b714-f2b3c2df565c.png)

**Comment by Mirkopoj** [comment]
Came to the office, the ubuntu machine is running nvim v0.8.0-dev, guess it builtit from source so I would be stuck with nvim v0.4.0.

**Comment by kevinhwang91** [comment]
`hi link NormalFloat NONE`

**Comment by Mirkopoj** [comment]
It worked! 
Thanks a lot, love this plugin, awesome work.
