### ISSUE TITLE
rnvimr doesn't focus the opened file/buffer?

### ISSUE THREAD

**Issue by gacallea** [kevinhwang91/rnvimr#128]
- `nvim -v`: 

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

- Operating system/version: **macOS 12.6.1**

- `nvim +'checkhealth rnvimr'`: 
```
not avaiable in LunarVim?
```

**Describe the bug**
not sure this is a bug or my misconfiguration, but when I open a file (`enter` or `l`), the opened buffer is not focused. the focus remains on the already previously opened file/buffer.

**To Reproduce using `nvim -u mini.vim`**

my lunarvim config, just in case: [https://github.com/gacallea/lunarvim](https://github.com/gacallea/lunarvim)

specific to rnvimr: [https://github.com/gacallea/lunarvim/blob/main/lua/plugins.lua#L8-L18](https://github.com/gacallea/lunarvim/blob/main/lua/plugins.lua#L8-L18)

1. launch rnvimr
2. open file
3. focus is on old file

**Expected behavior**
to have the newly opened file/buffer focused instead

**GIF**
![rnvimr](https://user-images.githubusercontent.com/3269984/203054601-31419d6c-8da5-4d16-b589-7df2206bd73f.gif)

**Comment by kevinhwang91** [comment]
Can't reproduce the issue, maybe your config issue.

**Comment by gacallea** [comment]
@kevinhwang91 thank you for the quick test/reply, I appreciate :)

any suggestions where to look? any particular config/option? i suspect this may be upstream (lunarvim).

cheers :)

**Comment by gacallea** [comment]
oh, I meant rnvimr config that could be clashing. like that is set, but overridden/bypassed somehow? :)

**Comment by kevinhwang91** [comment]
No valid info about that, you should use mini config to make sure rnvimr work as expected and add your rnvimr config.
If everything is fine, put them into lunarvim and find culprit plugin.

**Comment by gacallea** [comment]
I've found it :) it's [minimap](https://github.com/wfxr/minimap.vim/)! :)

I did add `rnvimr` to the [block/close options](https://github.com/wfxr/minimap.vim/#--options) but it aint working. what is the correct "name" to use? apparently rnvimr ain't working here.

```
vim.cmd("let g:minimap_block_buftypes =  [ 'nofile', 'nowrite', 'quickfix', 'terminal', 'prompt' ]")
vim.cmd("let g:minimap_close_buftypes =  [ 'nofile', 'nowrite', 'quickfix', 'terminal', 'prompt' ]")
vim.cmd("let g:minimap_block_filetypes = [ 'packer', 'bufferline', 'telescope', 'alpha', 'netrw', 'rnvimr', 'trouble', 'diffview', 'goto-preview', 'lazygit' ]")
vim.cmd("let g:minimap_close_filetypes = [ 'packer', 'bufferline', 'telescope', 'alpha', 'netrw', 'rnvimr', 'trouble', 'diffview', 'goto-preview', 'lazygit' ]")
```

cheers

**Comment by gacallea** [comment]
I found this old issue that is related. there is some incompatibility that has to do with rnvimr consider minimap as new window, allegedly. https://github.com/wfxr/minimap.vim/issues/71

**Comment by kevinhwang91** [comment]
I will check it out later, maybe can be compatible with minimap.vim.
