### ISSUE TITLE
Question about Ueberzug

### ISSUE THREAD

**Issue by farzadmf** [kevinhwang91/rnvimr#134]
Sorry if I'm not following the template, since it's mostly a question rather than a bug.

Now that [ueberzug](https://github.com/seebye/ueberzug) is gone (literally!), I was wondering what happens with the dependency this plugin has on it. I know it's optional, but still 🙂

Is there any fork of Ueberzug that can be used?

Thank you and again, apologies for not filling out the template. Feel free to not answer 🙂

**Comment by kevinhwang91** [comment]
> Is there any fork of Ueberzug that can be used?

Not yet, but `pip3 install ueberzug` should work.

You can install it from source code: `git clone git@github.com:seebye/ueberzug.git && cd ueberzug && git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) && pip3 install .`
