### ISSUE TITLE
Base directory of other tabs changes when opening a file in a different tab

### ISSUE THREAD

**Issue by twidxuga** [kevinhwang91/rnvimr#135]
- `nvim --version`: NVIM v0.9.0-dev-429+g10c50d9f3
- Operating system/version: Arch (Linux 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux)
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check

OS ~
- OK Name: Linux

Ranger ~
- OK Version: ranger 1.9.3

Python ~
- OK Version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]

Pynvim ~
- OK Version: 0.4.3

Ueberzug (optional) ~
- OK Ueberzug is ready

RPC ~
- OK RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
When dealing with multiple tabs in Neovim, each with a different base directory set using `:tcd <dir name>`, opening a file with rnvimr in one tab can change the base directory of the previous tab that was visited. 

Example: tab 1 has base folder A, tab 2 has base folder B, If I open a file in tab 2 nothing happens, but if afterwards we open a file in tab 1 then base folder of tab 2 becomes A instead of B.

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
call plug#end()

let g:rnvimr_vanilla = 0
let g:rnvimr_enable_ex = 1

nnoremap <silent> - :RnvimrToggle<CR>
nnoremap <silent> <leader>- :e .<CR>
```

1. Open nvim and change the base directory with `:tcd A` (tab 1)
2. Create a new tab with `:tabnew` and change the base directory with `:tcd B` (tab 2)
3. Open a file in tab 2 with nvimr
4. Check that the base directory of both tabs is still different with `:pwd`, changing between tabs with `gt`.
5. Open a file in tab 1 with nvimr
6. Check that the base directory of tab 1 remains the same BUT the base directory of tab 2 has changed to A, therefore both tabs have the same base directory now!

**Expected behaviour**
No unexpected changes of base folder for other tabs should occur when opening files in a tab.

**Comment by kevinhwang91** [comment]
Thanks, fixed.
