### ISSUE TITLE
Ranger didn't jump folder at first under a specific situation.

### ISSUE THREAD

**Issue by ysl2** [kevinhwang91/rnvimr#136]
Ranger didn't jump folder at first under the case below.

```
folder0
    |--file0.txt
folder1
    |--file1.txt
```

1. Enter `folder0` and use nvim to open `file0.txt`.

    ```
    cd folder0
    nvim file0.txt
    ```

2. Open `file1.txt` directly in nvim.

    ```
    # In neovim command below:
    :e ../folder1/file1.txt
    ```

3. Open ranger, and the folder is `folder0` but `folder1` is expected.

4. Reopen ranger, it will jump to `folder1`.

**Comment by kevinhwang91** [comment]
Can't reproduce it, please use github template.
