### ISSUE TITLE
Rnvimr not triggering ftplugin

### ISSUE THREAD

**Issue by Bekaboo** [kevinhwang91/rnvimr#138]
- `nvim --version`:
- Operating system/version:
- `nvim +'checkhealth rnvimr'`: 
```

==============================================================================
rnvimr: health#rnvimr#check

OS ~
- OK Name: Linux

Ranger ~
- OK Version: ranger-master 

Python ~
- OK Version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]

Pynvim ~
- OK Version: 0.4.3

Ueberzug (optional) ~
- OK Ueberzug is ready

RPC ~
- OK RPC echo: Neovim send "Give me five!" and receive "Give me five!"


```
**Describe the bug**

I want to set some special rule for rnvimr window. I created a file `rnvimr.lua` under `~/.config/nvim/ftplugin`, but it is never called when rnvimr is opened. Similar floating terminal plugins like [vim-floaterm](https://github.com/voldikss/vim-floaterm) or [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) do not have the similar issue.

**To Reproduce using `nvim -u mini.vim`**

N/A. This issue is related to ftplugin.

1. In `~/.config/nvim/ftplugin/rnvimr.lua`, write `vim.notify('rnvimr ftplugin fired', vim.log.levels.WARN)`
2. In nvim, open rnvimr
3. Check messages to see if rnvimr ftplugin is fired.

**Expected behavior**

`~/.config/nvim/ftplugin/rnvimr.lua` should be executed.

**Comment by kevinhwang91** [comment]
Can't reproduce.
