### ISSUE TITLE
Command not found: AttachFile

### ISSUE THREAD

**Issue by letscho123** [kevinhwang91/rnvimr#139]
When I open `RnvimrToggle` I get the message 
```
Command not found: AttachFile
```
Also opening a file in Rnvimr only opens it in the floating window and `RnvimrResize` gives the error message
```
Error detected while processing function rnvimr#resize:
line    2:
E5555: API call: Wrong type for argument 1 when calling nvim_win_is_valid, expecting Window
```

**My config**
Neovim 0.8.2, Astronvim 2.11.8, Fedora 37
```
  1 rnvimr: health#rnvimr#check
  2 ========================================================================
  3 ## OS
  4   - OK: Name: Linux
  5 
  6 ## Ranger
  7   - OK: Version: ranger 1.9.3
  8 
  9 ## Python
 10   - OK: Version: 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
 11 
 12 ## Pynvim
 13   - OK: Version: 0.4.3
 14 
 15 ## Ueberzug (optional)
 16   - WARNING: Ueberzug is not found in Python Lib
 17 
 18 ## RPC
 19   - ERROR: RPC: timeout 3s
```
```
:echo $NVIM_LISTEN_ADDRESS
/run/user/1000/nvim.191609.0
```

I would be grateful for any help!

**Comment by kevinhwang91** [comment]
Have you installed `pynvim`?

**Comment by letscho123** [comment]
Yes, as shown in checkhealth.

**Comment by kevinhwang91** [comment]
Does your py is under sys path? The lib should be the same as your py ENV.

**Comment by letscho123** [comment]
I found the issue. `ranger-fm` was installed under `/usr/lib/python3.11/site-packages/` and `pynvim` under `~/.local/lib/python3.11/site-packages`.
Using pip to uninstall `ranger-fm` and reinstall in `.local` fixed it. Now the plugin is working :)

Thanks for the great plugin!
