### ISSUE TITLE
s:reopen_win() method will trigger my X shortcut key

### ISSUE THREAD

**Issue by 178me** [kevinhwang91/rnvimr#140]
- `nvim --version`: NVIM v0.8.2
- Operating system/version: Arch
- `nvim +'checkhealth rnvimr'`: 
```
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - OK: Ueberzug is ready

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"

```
**Describe the bug**
s:reopen_win() method will trigger my X shortcut key

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_vanilla = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

1. first open ranger
2. toggle close
3. toggle open

**Expected behavior**
Do not trigger shortcut key

**Screenshots**
![image](https://user-images.githubusercontent.com/50314769/218443768-5f937020-c887-425a-83aa-3c0094b1dfa7.png)

**Additional context**
After troubleshooting, here is the shortcut key that let me trigger X
![image](https://user-images.githubusercontent.com/50314769/218444401-88f79013-f2f2-4527-9f01-f87d8dce6fd1.png)
I don't know what he can do

**Comment by kevinhwang91** [comment]
What's the first char of the fired key sequence?

**Comment by 178me** [comment]
X

**Comment by kevinhwang91** [comment]
Reproduced.

**Comment by kevinhwang91** [comment]
The culprit is that “<Nul>" become `0x80 0xff 0x58`.

**Comment by 178me** [comment]
It looks like I thought. Thank you very much for your update
