### ISSUE TITLE
support for ueberzugpp

### ISSUE THREAD

**Issue by dongdongbh** [kevinhwang91/rnvimr#141]
[ueberzugpp](https://github.com/jstkdng/ueberzugpp) is a command line utility written in C++ which allows to draw images on terminals by using child windows or using sixel on supported terminals. This is a drop-in replacement for the now defunct [ueberzug](https://github.com/seebye/ueberzug) project.

I use it on my ranger, and it works out-of-box. But it do not directly work on [rnvimr](https://github.com/kevinhwang91/rnvimr). Can rnvimr add support for ueberzugpp?

**Comment by kevinhwang91** [comment]
Look like doesn't work for me. I am ArchLinux user.

**Comment by dongdongbh** [comment]
I posted an [issue](https://github.com/jstkdng/ueberzugpp/issues/9) on ueberzugpp, its syntax is a bit different from    the original ueberzug. But I use it on plain ranger in cli, it just worked. I use it on Ubuntu 20.04 BTY.

**Comment by kevinhwang91** [comment]
After upgrading it, ranger can preview the image, but can't switch images after two previews. It doesn't seem stable enough for me. I leave this issue and will support it if the time is ripe.

**Comment by dongdongbh** [comment]
OK, it can switch pictrues as many as possible on my computer. Anyway, just wait a bit, seems the maitainer is actively developing.

**Comment by jstkdng** [comment]
@kevinhwang91 does your terminal support sixel? then perhaps that's the issue. Current ranger doesn't support Ü++'s sixel implementation, I've opened a PR on ranger's side but no luck so far https://github.com/ranger/ranger/pull/2786.

**Comment by kevinhwang91** [comment]
@jstkdng Sorry, after rebooting my system, it works fine outside nvim terminal, but can't work with ranger inside nvim. Does ueberzugpp use a protocol to communicate with images?

**Comment by jstkdng** [comment]
U++ can receive commands through stdin (og ueberzug) or tcp (newer).
It's weird that ranger in neovim doesn't spawn U++. Is the config being modified?

**Comment by kevinhwang91** [comment]
You can reproduce the issue follow below steps:
1. Start ranger inside nvim:  `nvim --clean +'term ranger --clean' +'startinsert'`;
2. Enable preview image in ranger: `set preview_images_method ueberzug` and `set preview_images true`;
3. Browse images;

**Comment by jstkdng** [comment]
Yes, I'm able to reproduce the issue.
It seems U++ can't correctly find the size in pixels of the neovim terminal. And it's crashing as soon as it is spawned

**Comment by jstkdng** [comment]
The issue should be fixed on v2.3.0

**Comment by kevinhwang91** [comment]
Confirmed. Rnvimr doesn't need to change anything. Please add an installation section for ueberzugpp, so Rnvimr can add docs for the new optional.

**Comment by jstkdng** [comment]
Hmm, right now the only way to install is to build it from source. There's the AUR package I'm maintaining but I have no package for other distributions.
Maybe a flatpak could be built for other distributions but I'm gonna have to do some research.
