### ISSUE TITLE
Considerable lag when pressing j due to a key mapping.

### ISSUE THREAD

**Issue by sidzwans** [kevinhwang91/rnvimr#144]
- `nvim --version`: v0.9.0-dev-1100+g1dd2424b12
- Operating system/version:  Arch Linux (Rolling)/Sway 1.81
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check

OS ~
- OK Name: Linux

Ranger ~
- OK Version: ranger 1.9.3

Python ~
- OK Version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]

Pynvim ~
- OK Version: 0.4.3

Ueberzug (optional) ~
- WARNING Ueberzug is not found in Python Lib

RPC ~
- OK RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
There is a considerable lag when pressing 'j' to go down the tree.
It is caused by this keymap:
`vim.keymap.set('t', 'jk', '<C-c>')`

Key 'k' was not pressed.

**To Reproduce using `nvim -u mini.lua`**

Example:
`cat mini.lua`
```vim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    'kevinhwang91/rnvimr',
  },
})

vim.keymap.set('t', 'jk', '<C-c>')

```

1. Open Nvim
2. Execute :RnvimrToggle
3. Press 'j'

**Expected behavior**
Key 'k' was never pressed but only key 'j'. The mapping should not be executed.Therefore, there shouldn't be any lag when pressing j to go down.

**Comment by kevinhwang91** [comment]
```vim
    aug RnvimrKeyMap
        au!
        au FileType rnvimr tnoremap <buffer><silent><nowait> j j
    aug END
```
