### ISSUE TITLE
Mouse scroll up/down freezes Rnvimr

### ISSUE THREAD

**Issue by Zeioth** [kevinhwang91/rnvimr#146]
- `nvim --version`: 0.9.0
- Operating system/version: Arch
- `nvim +'checkhealth rnvimr'`: 
```
   2   rnvimr: health#rnvimr#check
   3   
   4   OS
   5   - OK Name: Linux
   6   
   7   Ranger
   8   - OK Version: ranger-master 
   9   
  10   Python
  11   - OK Version: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
  12   
  13   Pynvim
  14   - OK Version: 0.4.3
  15   
  16   Ueberzug (optional)
  17   - WARNING Ueberzug is not found in Python Lib
  18   
  19   RPC
  20   - OK RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
Using mouse scroll up/down on RnvimToggle causes the modal window to become irresponsive.

1. Run RnvimToggle
2. Use the mouse to scroll up/down through your files in ranger.

**Expected behavior**
Ranger scrolls through the files (as, in normal ranger)

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/rnvimr/issues/58
