### ISSUE TITLE
Question: How can I open ranger files in a new buffer instead of in the floating window?

### ISSUE THREAD

**Issue by Zeioth** [kevinhwang91/rnvimr#148]
![screenshot_2023-05-16_22-08-15_965671644](https://github.com/kevinhwang91/rnvimr/assets/3357792/def02479-49f9-43d9-980d-f464099fe501)

**Comment by Zeioth** [comment]
I'm not sure how to debug it. It says health ok. I wil keep looking into the code.

**Comment by kevinhwang91** [comment]
The parent directory of `pynvim` should be installed in the same path as `ranger`. You can run `eval import pynvim` in ranger to check out.

**Comment by kevinhwang91** [comment]
I guess your open candidate is `nvim`.

Q: Couldn't open some special types of files by using `Enter` or `l` in Ranger.

A: Please follow the below steps to solve this issue:

1. The behavior of opening the file in Ranger depends on `rifle.conf`.
   Press `r` to make sure that the `${VISUAL:-$EDITOR} -- "$@"` is the best candidate in Ranger.
2. If the case 1 is false, change the code in `rifle.conf` like that:

**Comment by Zeioth** [comment]
# Tried launching like this
    VISUAL=nvim EDITOR=nvim nvim

    # With this on rifle.conf
    mime ^text,  label editor         = nvim -- "$@"

rnvimr opens nvim, the problem is it does it in a floating anidated window instead of nvim itself.  The plugin https://github.com/rafaqz/ranger.vim works as expected. The issue is not of ranger but of this plugin.

Please could you tell me what ranger/pynvim/nvim versions are you running?

**Comment by kevinhwang91** [comment]
RTFM.

**Comment by Zeioth** [comment]
I found several other issues with the same problem. Solved with:

    let g:rnvimr_vanilla = 1
