### ISSUE TITLE
Passing an env var to rnvimr_ranger_cmd fails

### ISSUE THREAD

**Issue by Zeioth** [kevinhwang91/rnvimr#149]
## Works
```lua
vim.g.rnvimr_ranger_cmd = { "ranger", "--cmd=set draw_borders both" }
```
## Fails
Trying to open ranger with an env var
``` lua
vim.g.rnvimr_ranger_cmd = { "foo=bar", "ranger", "--cmd=set draw_borders both" }
```

![screenshot_2023-05-23_05-57-56_974095939](https://github.com/kevinhwang91/rnvimr/assets/3357792/48d301b9-ef4f-46b3-ab61-1a0c41901778)

**Comment by Zeioth** [comment]
What I want in reality is to be able to call my terminal from inside rnvimr. I've tried:

ranger-wrapper.sh
    
    TERMCMD="foot" ranger

rnvimr
     
    vim.g.rnvimr_ranger_cmd = { "ranger-wrapper.sh" }

![screenshot_2023-05-23_16-39-07_384374048](https://github.com/kevinhwang91/rnvimr/assets/3357792/e334ca20-5044-4c56-8e84-d425f4cc81d1)


And it works correctly. The only bug I experience is after closing rnvimr, the window doesn't close. So I imagine this is not actually supported by rnvimr.


![screenshot_2023-05-23_16-37-18_920774735](https://github.com/kevinhwang91/rnvimr/assets/3357792/cf0082e8-cd65-475e-9580-3935560a5058)

**Comment by kevinhwang91** [comment]
```bash
#!/usr/bin/env bash
TEST=foo ranger "$@"
```

**Comment by Zeioth** [comment]
It works that way thank you!!
