### ISSUE TITLE
< C-T > and < C-X > and < C-V > is not effected

### ISSUE THREAD

**Issue by miko2009** [kevinhwang91/rnvimr#15]
I'm using neovim, and I've also installed Ranger. After installing your plug-in, I can open the file with the Enter key, but it is invalid to use < C-T > and < C-X > and < C-V >. These three keys have no binding function.

**Comment by kevinhwang91** [comment]
1. What's your version of neovim and python and ranger?

2. How about running `SplitAndEdit vsplit` inside ranger? Will neovim do an action like `vsplit` and open the file selected by ranger?

**Comment by miko2009** [comment]
1. neovim is  v0.4.3 . python  is 2.7 . ranger  1.9.3.
2. 
![image](https://user-images.githubusercontent.com/20310560/79949916-e041c400-84a8-11ea-8c2a-e11abdcfe3ae.png)  
3. no

**Comment by kevinhwang91** [comment]
python 3 is required already stated in the readme.

**Comment by miko2009** [comment]
i had upgraded my python version . but it didn't work.

**Comment by kevinhwang91** [comment]
Are you using Mac？If yes, please install ranger via `pip install ranger-fm` instead of `brew`.

https://github.com/kevinhwang91/rnvimr/issues/6

**Comment by miko2009** [comment]
yes , i brew uninstall ranger and pip3 install ranger-fm .  but it doesn't work.  "  FM  has no attribute client" is hint when use ranger in neovim

**Comment by kevinhwang91** [comment]
Had you synchronized the plugins(the lib of rnvimr is also a plugin of ranger) via `:RnvimrSync`?
Make sure that the files `action.py  hacks.py  host.py  service.py` are in `~/.config/nvim/plugged/rnvimr/ranger/plugins`.

**Comment by miko2009** [comment]
yes i had .  those files in ~/.config/nvim/plugged/rnvimr/ranger/plugins.

**Comment by kevinhwang91** [comment]
Please `pip3 install pynvim`. pynvim is required also stated in readme.

**Comment by miko2009** [comment]
there  are some errors in “sudo pip3 install ueberzug ”   。 i can't resolve it

**Comment by miko2009** [comment]
Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-83hz25ic/ueberzug/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-83hz25ic/ueberzug/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-dtjhuha7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/ueberzug Check the logs for full command output.

**Comment by kevinhwang91** [comment]
ueberzug is only supported in X11 in Linux, which is an optional requirement for rnvimr. If you can open the file via `<C-txv>` please close this issue.

**Comment by miko2009** [comment]
<C-txv> doesn't work

**Comment by kevinhwang91** [comment]
Why do you want to Install ueberzug? I think to install pynvim will work.

**Comment by miko2009** [comment]
i had install pynvim

**Comment by kevinhwang91** [comment]
What's the message from the display_log inside ranger? Press `W` or input `display_log` in ranger's console.

**Comment by miko2009** [comment]
can not find module 'pynvim'

**Comment by kevinhwang91** [comment]
Please install pynvim properly.

**Comment by kevinhwang91** [comment]
You should make sure python version in the output of `ranger --version`  is 3 instead of 2.
And then run `python3  -c 'import pynvim` check out pynvim is installed..

**Comment by miko2009** [comment]
yes i am sure 
ranger version: ranger 1.9.3
Python version: 3.7.3 (default, Apr  7 2020, 14:06:47) [Clang 11.0.3 (clang-1103.0.32.59)]
Locale: zh_CN.UTF-8

~/.config/nvim » python3 -c 'import pynvim'                                              
------------------------------------------------------------------------------------------------------------
~/.config/nvim »

**Comment by kevinhwang91** [comment]
Run `eval os.sys.path` inside the ranger's console and open display log. Make sure the root lib location of pynvim is included from the list of output.

**Comment by kevinhwang91** [comment]
In the end, I hope you solve the issue of installing pynvim by yourself. Good luck.

**Comment by kevinhwang91** [comment]
![image](https://user-images.githubusercontent.com/17562139/79985517-4d6f4c80-84dd-11ea-852a-7e7a68a11d75.png)
@miko2009 Don't comment on the showcase issue. It's just to show the images of this repo.

I will delete your comment inside that issue, I'm so sorry.

**Comment by haha405pan** [comment]
> Had you synchronized the plugins(the lib of rnvimr is also a plugin of ranger) via `:RnvimrSync`?
> Make sure that the files `action.py hacks.py host.py service.py` are in `~/.config/nvim/plugged/rnvimr/ranger/plugins`.

Hi Mr wang,
I had same issue and didn't find those file in the plugins file. I was trying to synchronize the plugin via typing `RnvimrSync` in the neovim but the command could not found. 

For your reference, I am currently using Arch Linux, 
- [ ] installed neovim and ranger via pacman
- [ ] installed pynvim via pip 
- [ ] `health check` shows no problem

**Comment by kevinhwang91** [comment]
> > Had you synchronized the plugins(the lib of rnvimr is also a plugin of ranger) via `:RnvimrSync`?
> > Make sure that the files `action.py hacks.py host.py service.py` are in `~/.config/nvim/plugged/rnvimr/ranger/plugins`.
> 
> Hi Mr wang,
> I had same issue and didn't find those file in the plugins file. I was trying to synchronize the plugin via typing `RnvimrSync` in the neovim but the command could not found.
> 
> For your reference, I am currently using Arch Linux,
> 
> * [ ]  installed neovim and ranger via pacman
> * [ ]  installed pynvim via pip
> * [ ]  `health check` shows no problem

`RnvimrSync` has been removed, If FAQ didn't work for you, please open a new issue.
