### ISSUE TITLE
mouse click not working

### ISSUE THREAD

**Issue by JosefLitos** [kevinhwang91/rnvimr#151]
After last commit, scrolling works beautifully, but clicking unfortunately still does nothing.

tried with neovim 0.9

**Comment by Zeioth** [comment]
Good point, I didn't noticed. I'm not 100% sure if this is a limitation of neovim. I will test the patch with different mouse modes, instead of setting 

    mouse=""

If that doesn't do it, I will report it to neovim bug tracker.

**Comment by kevinhwang91** [comment]
I think it's hart to fix. Need capture current cursor and fire click action manually.

**Comment by Zeioth** [comment]
I've found a better solution. But it is something that might not work for all users, as it depends on their term codes: https://github.com/neovim/neovim/issues/21106

``` sh
  # This will only work if mouse=a is setted.
  printf "\x1b[?1000h" # On the term, set term code before launching rnvimr
```

That implementation gives 100% mouse support (left click, right cllick, mid click, and scroll) on xterm-256color terminals and tmux. I propose this over the current implementation, but as an opt-out option so users using terminals that doesn't use xterm-256color can still implement their own solution by setting the option to false.

At very least it should work on all modern terminals using xterm-256color. I'll prepare a PR later so we can test it.

**Comment by kevinhwang91** [comment]
I review the thread from core you mention and it inspires me a lot.
We can just write `\x1b[?1000h` to stderr of ranger terminal. However, we can't get the stderr file handle from the vimscript API, using a Lua luv API can write the code sequence to stderr file handle. We can also send sequence after ranger is stable, but it looks like a bad solution.

Why not send the code sequence before running ranger?
Here is the related answer https://github.com/kevinhwang91/rnvimr/pull/114.

**Comment by kevinhwang91** [comment]
Found  `nvim_get_chan_info` API get dev handle.

**Comment by JosefLitos** [comment]
Works beautifully on `foot`, thanks a lot!

**Comment by Zeioth** [comment]
This is so awesome. Thank you for implementing it @kevinhwang91. I was struggling.
