### ISSUE TITLE
mouse_support broken

### ISSUE THREAD

**Issue by fecet** [kevinhwang91/rnvimr#152]
```
Error detected while processing function rnvimr#toggle[16]..rnvimr#init[29]..rnvimr#enable_mouse_support:
line   23:
E122: Function <SNR>138_set_mouse_with_rnvimr already exists, add ! to replace it
```

**Comment by Zeioth** [comment]
Related to #151

**Comment by Zeioth** [comment]
@feced Under what circumstances does that happen? Could you provide more info?

The function is defined when rnvimr launches
https://github.com/kevinhwang91/rnvimr/blob/8021cc2ea47a4a3c1cee05a555b3368c8e1d67be/autoload/rnvimr.vim#L185
 that shouldn't normally happen.

**Comment by fecet** [comment]
More info every first call of "RnvimrToggle" works, but if I quit it with ":q<CR>" in neovim(I map it by key `Q`)  or open a file instead of quit with enter ":q" in ranger's command mode. The second "RnvimrToggle" will raise this error and I have to reload nvim.
