### ISSUE TITLE
[ERROR] can't open file

### ISSUE THREAD

**Issue by ryannewcomer** [kevinhwang91/rnvimr#153]
- `nvim --version`:v0.9.1
- Operating system/version: Debian 11 on window 11 wsl 2
- `nvim +'checkhealth rnvimr'`: 

![image](https://github.com/kevinhwang91/rnvimr/assets/88273136/f3275781-94cd-410b-adbf-a4b692ee91dd)

**Describe the bug**
after a open rnvimr use RnvimrToggle, the ranger window open, then i open keymap.lua file, but it said no file or direction : 'file'

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`
```lua
-- i am using lazy
{ 
"kevinhwang91/rnvimr",
lazy = false,
},
```

1.clone https://github.com/alpha2phi/neovim-pde
2.open nvim ( without problem
3.install rnvimr
4. restart nvim
5. open rnvimr with RnvimrToggle
6. found a file to open with enter
7. error 😢 

**Expected behavior**
it should open the file!!!

**Screenshots**
![Screenshot 2023-06-02 183230](https://github.com/kevinhwang91/rnvimr/assets/88273136/aaa4c98e-5de3-48fd-9301-a18731681f46)

**Additional context**
no

**Comment by kevinhwang91** [comment]
Type `W` in ranger to show detail.

**Comment by ryannewcomer** [comment]
![image](https://github.com/kevinhwang91/rnvimr/assets/88273136/acb26853-de09-4864-a47e-44c5699381b4)

**Comment by kevinhwang91** [comment]
Look like you are missing `file` command. I'm not sure that ranger can work under WSL.

**Comment by ryannewcomer** [comment]
ok, i restart the terminal and it seems to be working
![image](https://github.com/kevinhwang91/rnvimr/assets/88273136/b9d35433-bfdc-470c-9f0e-9c04175f45b3)
i just open a python file for example, it this normal?

**Comment by ryannewcomer** [comment]
also, the file previews doesn't work

**Comment by kevinhwang91** [comment]
Make sure ranger work fine under WSL outside Neovim
