### ISSUE TITLE
Ranger does not execute mappings that use control

### ISSUE THREAD

**Issue by jfab-123** [kevinhwang91/rnvimr#155]
- `nvim --version`: 0.9.2
- Operating system/version: 6.5.3-arch1-1
- `nvim +'checkhealth rnvimr'`: 
``` 

==============================================================================
rnvimr: health#rnvimr#check

OS ~
- OK Name: Linux

Ranger ~
- OK Version: ranger 1.9.3

Python ~
- OK Version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
  Locale: en_US.UTF-8

Pynvim ~
- OK Version: 0.4.3

Ueberzug (optional) ~
- OK Ueberzug is ready

RPC ~
- OK RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
I have a function that executes fzf defined for ranger. In rc.conf I mapped it with ```map <C-o> fzf```. When I press ```<C-o>``` in floating ranger, nothing happens. If I change the mapping to just ```f``` for example, the mapping works. 
Actually thinking about it, f is a better mapping anyways, but I just wanted to ask if this was intended or if mappings using control are not allowed.

1. Just use a mapping with control in rc.conf, like ```map <C-o> console delete```.

**Expected behavior**
Mappings defined with control work.

**Comment by kevinhwang91** [comment]
Can't reproduce it, make sure that `tmap <c-o>` in the floating window output `No mapping found`.
