### ISSUE TITLE
关于对此插件的改进建议

### ISSUE THREAD

**Issue by theniceboy** [kevinhwang91/rnvimr#2]
你好！首先感谢你编写的rnvimr插件。我很喜欢你利用nvim特性配合ranger达成的用户体验。我之前使用的是[ranger.vim](https://github.com/francoiscabrol/ranger.vim)，我认为rnvimr会比ranger.vim优秀很多，但rnvimr目前存在一些我认为需要得到解决的问题。

#### 1. 在ranger模式下，对与`ESC`键的处理
使用`:RnvimrToggle`打开ranger后，键入`g`（或其他用户定义的组合键），ranger会在底部弹出提示框来显示可能的组合键（如`gg`）。正常情况下，用户可以通过`ESC`键来取消组合键（同时关闭提示框）。**但在rnvimr中，ESC会直接关闭ranger**。这会导致很大的不便。（ranger.vim则没有这个问题）

#### 2. 自动更新ranger配置文件
拿我个人的ranger使用习惯来说，我经常会打开ranger配置文件，添加或修改一些cd特定目录的快捷键。这很大程度上提高了我的工作效率，因为我可以随时跳转到我常用的文件夹。当我的ranger配置文件更新后，ranger.vim也会使用最新的配置文件来打开ranger（因为ranger.vim只不过是打开了一个终端并运行`ranger —choosefiles`而已）。而对于rnvimr，我则需要手动`:RnvimrSync`。这很不符合用户逻辑，因为对于用户来说，我们打开的应该是同一个ranger。

一个次优解决方案是在每次更新ranger配置后在插件目录下运行`make sync`，（可以用类似`ENTR`这种程序来检查文件更新），但最好还是有一个比较优雅的解决方案。

#### 3. 当nvim的`cwd`改变的时候，rnvimr应该显示新的路径
我的[init.vim](https://github.com/theniceboy/nvim/blob/master/init.vim#L44)让我的nvim自动把当前的buffer的目录（如果存在）设为当前的`cwd`（Current Working Directory）。所以我在打开ranger.vim的时候，ranger.vim会自动把目录设置成我当前buffer所在的目录。

每次ranger.vim都会重新启动ranger，**速度很慢**。rnvimr只需要启动ranger一次。**但是，`:RnvimrToggle`不会根据nvim的`cwd`来改变ranger浏览的目录。我认为这是一个比较大的问题。**

#### 4. 更简单易懂的文档
目前rnvimr的文档还是略过复杂，我们可以进一步讨论对于README的改进方法。

#### 结语
再一次感谢你编写的插件。这个插件会提升包括我在内很多人的工作效率。我很愿意和你进一步的讨论。

— 陈为

**Comment by kevinhwang91** [comment]
非常感谢你的意见。

1.我这里的Esc并没有你所说的退出ranger。会单独启动ranger一样，取消提示框，并不会关闭ranger的悬浮窗口。建议检查neovim插件有没有冲突。

2.对于同步插件的问题，因为rnvimr是有自己的库的，也是ranger的‘插件’，如果把这些库放到正常的ranger配置路径下，那么shell启动ranger将会异常。其实不同用户对于在neovim里需要简洁还是强大的ranger是不一样的，目前这个功能得观察用户的反馈。

3.你可以尝试在ranger里面按q，这里会有一个逻辑会产生attach file。下一次toggle ranger的时候，ranger就会select你当前的buffer。

4. 这个确实可以改进，目前我自己用的是最简配置+取代netrw的配置而已。

**Comment by theniceboy** [comment]
感谢你的回复！

请忽略我的第一个建议，我才发现我在配置文件里写了`tnoremap <ESC> <c-c>`

对于同步配置问题，理解rnvimr不能在ranger路径里存放插件。我目前只能使用这个配置来解决同步配置的问题：
```
let g:rnvimr_ex_enable = 1
let g:rnvimr_pick_enable = 1
nnoremap <silent> R :RnvimrSync<CR>:RnvimrToggle<CR><C-\><C-n>:RnvimrResize 0<CR>
let g:rnvimr_presets = [{'width': 1.0, 'height': 1.0}]
```
貌似没有影响启动速度，我会继续测试。

关于第三个问题，我本以为按q会退出ranger导致下次`:RnvimrToggle`速度变慢（因为需要重新打开），但根据你的建议我发现速度并没有变慢。瞬间打开。完美。

这个repo值得更多的star。

**Comment by theniceboy** [comment]
@kevinhwang91 有兴趣的话可以b站发我一下你的联系方式，我想出个视频推广一下你的插件。发前我觉得有必要修改一下readme
