### ISSUE TITLE
E363: pattern uses more memory than 'maxmempattern'

### ISSUE THREAD

**Issue by ChristianChiarulli** [kevinhwang91/rnvimr#21]
I'm seeing the error on my mac but not linux,

one solution was to:

set mmp=2000

Increasing this also increases lag though so, it's not an ideal solution.

I though it was devicons but I was wrong

**Comment by kevinhwang91** [comment]
I can't believe this issue caused by rnvimr. rnvimr never use regex pattern in vimscript for now.

Please try this mini.vim.  nvim -u mini.vim.
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```
