### ISSUE TITLE
Opening a file, it stays inside the small window?

### ISSUE THREAD

**Issue by thepenguinthatwants** [kevinhwang91/rnvimr#23]
Hi!

I've tried your plugin ranger and neovim is nice, but the problem is that it doesnt open the file into the buffer instead it opens up inside the floating window. 

Any way to open it in nvim instead of staiying inside the floating window?

**Comment by kevinhwang91** [comment]
Rnvimr will automatically make ranger to open the file in neovim. I think this is your installation issue. What's your `:checkhealth rnvimr` output?

**Comment by thepenguinthatwants** [comment]
Sorry late response


    1 health#rnvimr#check
    2 ========================================================================
    3 ##·OS
    4 ··-·OK:·Name:·Linux
    5
    6 ##·Ranger
    7 ··-·OK:·Version:·ranger·1.9.3
    8
    9 ##·Python
   10 ··-·OK:·Version:·3.8.2·(default,·Apr··8·2020,·14:31:25)·[GCC·9.3.0]
   11
   12 ##·Pynvim
   13 ··-·OK:·Version:·0.4.1
   14
   15 ##·Ueberzug·(optional)
   16 ··-·WARNING:·Ueberzug·can·not·calibrate·properly·outside·Tmux.
   17 ····-·ADVICE:
   18 ······-·If·use·Rnvimr·without·Tmux,·please·upgrade·the·latest·version·of·Ueberzug
   19
   20 ##·RPC
   21 ··-·OK:·Install·lib·for·checkhealth·successfully
   22 ··-·OK:·RPC·echo:·Neovim·send·"Give·me·five!"·and·receive·"Give·me·five!"
   23 ··-·OK:·Clean·lib·for·checkhealth·successfully
   24
~

I dont understand how this should be run. Like in ranger I ran :eval os.getenv('VISUAL')
 It didnt give any output.
`eval os.getenv('VISUAL')`

**Comment by thepenguinthatwants** [comment]
Hi sorry! It seems to work.

Seems like its not possible to make it work like  tpope vinegar plugin that it start it closes the window when I've opened a file?

**Comment by kevinhwang91** [comment]
`:h rnvimr`
```
g:rnvimr_pick_enable
    Default: 0

    Enable Ranger to be hidden after picking a file.
    It will automatically attach file in next |:RnvimrToggle|.

```

**Comment by thepenguinthatwants** [comment]
Hi! 

Now I get it.. sorry I usually just create new empty files in ranger.

Seems like this works right if the files are not empty. Tho its a bug in that part that it opens up empty files inside the small window.

**Comment by kevinhwang91** [comment]
ranger open file using `rifle`. Already stated in the readme.

> Q: Couldn't open some special type of files by using Enter or l in Ranger.
A: Please follow below steps to solve this issue:
The behavior of openning the file in Ranger depends on rifle.conf. Press r to make sure that the ${VISUAL:-$EDITOR} -- "$@" is the best candidate in Ranger.
If the case 1 is false, change the code in rifle.conf like that:
-!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = ${VISUAL:-$EDITOR} -- "$@"
+!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|your_file_type = ${VISUAL:-$EDITOR} -- "$@"
execute:RnvimrSync to synchronize the rifle.conf just modified with Rnvimr.

If you want to open an empty file using `${VISUAL:-$EDITOR} -- "$@"`, you should change your rule of `rifle`.

**Comment by thepenguinthatwants** [comment]
OOh thanks. Sorry I somehow didnt get that earlier.

Is there also a way if I have multiple buffer in same window and open a file by rnvimr, is it possible to leave other buffer untouched and only change the current one?

**Comment by kevinhwang91** [comment]
Sorry for my inability to understand what you mean. Please explain clearly to me.

**Comment by thepenguinthatwants** [comment]
When I make a buffer split with <c-w><c-v> and open rnvimr to choose a file to open. It open up in the whole window instead of the chosen buffer.

**Comment by kevinhwang91** [comment]
Do you mean all buffers in nvim' window open the same file chose by ranger? If yes, I can't reproduce your issue.
Please try a mini.vim like this:
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

**Comment by keevee09** [comment]
Hi, I have the same issue. When I run rnvimr within nvim and <l> or <CR> to open the file in neovim,
it opens an instance of nvim in the rnvimr floating window rather than the running instance of nvim.
I am on xubuntu 18.04 with the latest neovim and ranger and a pyenv version of python3.7 in my shell.
When I run `:checkhealth`, `health#rnvimr#check` throws an error:
`ERROR: Failed to run healthcheck for "rnvimr" plugin. Exception: function health#check[21]..health#rnvimr#check[2]..<SNR>154_check_python_ranger, line 7
Vim(let) :E688: More targets than List items.

OK, I have answered the problem as it pertains to myself:
rnvimr finds the apt installed (old) version of ranger and tries to use it. I uninstalled this and installed the python package with pip instead.
I have cloned your git repository and linked to ranger.py to run ranger from the shell (because the Ubuntu Repository ranger is outdated).
Within nvim, the rnvimr looks for ranger and can't find this version --- the symlink to ranger.py is in ~/bin --- but it can find the `pip install ranger-fm` version which runs within nvim.

**Comment by kevinhwang91** [comment]
> Hi, I have the same issue. When I run rnvimr within nvim and try to open the file in nvim,
> it opens an instance of nvim in the rnvimr floating window rather than the running instance of nvim.
> I am on xubuntu 18.04 with the latest neovim and ranger and a pyenv version of python3.7 in my shell.
> When I run `:checkhealth`, `health#rnvimr#check` throws an error:
> `ERROR: Failed to run healthcheck for "rnvimr" plugin. Exception: function health#check[21]..health#rnvimr#check[2]..154_check_python_ranger, line 7
> Vim(let) :E688: More targets than List items.
> 
> OK, I have answered the problem as it pertains to myself:
> rnvimr finds the apt installed (old) version of ranger and tries to use it. I uninstalled this and installed the python package with pip instead.
> I have cloned your git repository and linked to ranger.py to run ranger from the shell (because the Ubuntu Repository ranger is outdated).
> Within nvim, the rnvimr looks for ranger and can't find this version --- the symlink to ranger.py is in ~/bin --- but it can find the `pip install ranger-fm` version which runs within nvim.


Specify your Ranger path to `g:rnvimr_ranger_cmd`.
> g:rnvimr_ranger_cmd
    Default: 'ranger'
    Use this command to run a process inside the floating window.
    It can mix some command of Ranger, such as 'ranger --cmd="xxx"'.
