### ISSUE TITLE
No module named greenlet

### ISSUE THREAD

**Issue by againxx** [kevinhwang91/rnvimr#24]
Great work!
I have a similar problem as #19, however I use conda instead of virtualenv.

When I used rnvimr in some project environment (which doesn't have pynvim and greenlet), the rnvimr complain `No module named greenlet`when I pressed `<Enter>` or `l`, however I have pynvim installed in my system python3 and `let g:python3_host_prog  = '/usr/bin/python3`, and I can still use `<C-t>` `<C-x>` and `<C-v>` to open files in tab, split and vsplit.

Besides, the newly added checkhealth feature also complains that pynvim is not found, but neovim provider says it's found.
![rnvimr1](https://user-images.githubusercontent.com/22728604/81464419-41c99880-91f4-11ea-8d70-0eb5ab685be3.png)
![rnvimr2](https://user-images.githubusercontent.com/22728604/81464423-455d1f80-91f4-11ea-8876-7158a2613d5b.png)

After I installed pynvim in conda environment, all problems are gone.
 
Is it a must to have pynvim installed in every conda environment?

**Comment by kevinhwang91** [comment]
I don't want to break the original mechanism of opening a file in ranger. Pressing `Enter` or `l` will execute file through `rfile` to use an external executable script, which is different from using `<c-t>` to open a file through inner function in ranger. 

The complaint about pynvim in checkhealth may be a bug, I should check the special path first, I will solve that issue soon.

What's the msg output for ranger inside floating window by input `:eval os.getenv('PYTHONPATH')`?

Is your path of pynvim inside the `PYTHONPATH`?

> Note: I fix #19 by exporting `PYTHONPATH` include site-packages of pynvim inside ranger to an external script to synchronize the pynvim in ranger with the external script. It's so weird that you can use pynvim inside ranger but can't export the `PYTHONPATH` env outside. (I don't use conda, I have no idea about the site-packages inside conda)

**Comment by kevinhwang91** [comment]
Some users found the installation of rnvimr is so cumbersome. So I wrote a checkhealth feature to hint the message for the user during the installation.

Env using virtualenv and conda and so on may make some issues caused by the different env between ranger and the external script. I think I should do the action of EDITOR inside ranger rather than in the external script. So I will delete the EDITOR file and use a dummy EDITOR. 
Maybe I will do this idea tonight.

**Comment by againxx** [comment]
The output of `:eval os.getenv('PYTHONPATH')` is my local python3.6 package folder in `~/.local/lib/python3.6/site-packages`, which contains `pynvim` and `greenlet` but not `ranger` 
(`ranger` is installed in /usr/local/lib/python3.6/dist-packages).
Anything else for me to check?

**Comment by kevinhwang91** [comment]
No, I will refactor code and solve this issue by using dummy EDITOR tonight.

**Comment by againxx** [comment]
I find only the `greenlet` package is needed for my conda environment.
Installing `pynvim` will install three packages `pynvim` `greenlet` and `msgpack`.
After I uninstall `pynvim` and `msgpack` in conda env. Rnvimr still wokrs as expected.

**Comment by againxx** [comment]
Thank you! Wait for your good news.

**Comment by kevinhwang91** [comment]
Could you try again? But the checkhealth hasn't fixed yet.

**Comment by againxx** [comment]
It works great! I can now use it in any conda environment.
