### ISSUE TITLE
Devicons and first character of the line is not visible.

### ISSUE THREAD

**Issue by zer09** [kevinhwang91/rnvimr#25]
Everything is working if ranger is called directly from the terminal emulator, but if called from `nvim` the `devicons` is not showing up and if the `draw_borders` in `rc.conf` is set to `set draw_borders both` or `set draw_borders separators`, then every first character of the lines in the preview is missing.

**System Details:**
_OS_: Pop Os 19.10
_Terminal_: Alacritty 0.4.1 and Gnome Terminal 3.34.2
_Font_: SF Mono Powerline light, also tested using Fira Mono for Powerline
_Ranger config:_ everything is default except

- default_linemode devicons
- set vcs_aware true
- set preview_images true
- set preview_images_method ueberzug
- set draw_borders both
- Also I uncomment the video and pdf section on the scope.sh

_rnvimr config:_

- let g:rnvimr_ex_enable = 1
- let g:rnvimr_pick_enable = 1
- let g:rnvimr_draw_border = 1
- let g:rnvimr_bw_enable = 1
- let g:rnvimr_presets = [ { 'width': 0.950, 'height': 0.900 } ]

Also added this to the config `let g:vimtex_compiler_progname = 'nvr'` for to make all green on `nvim +'checkhealth rnvimr'`

**Expected Behavior:**
Devicons should show and all text on preview should be shown, like what ranger is showing if called directly from the terminal.
![Screenshot from 2020-05-15 07-13-38](https://user-images.githubusercontent.com/780780/81995066-e710c080-967b-11ea-963f-7eb636d62801.png)

**Actual Behavior:**
Devicons is not shown and the first character on every line is missing.
![Screenshot from 2020-05-14 08-39-07](https://user-images.githubusercontent.com/780780/81995123-0ad40680-967c-11ea-8857-fe143581c2ba.png)

If there's any details I missed, I will be happy to provide.

Thanks

**Comment by kevinhwang91** [comment]
Thank you for the feedback and sufficient info. I can reproduce this issue easily. I had solved this issue but doesn't commit. I will add some features to commit together tonight.

**Comment by kevinhwang91** [comment]
I fix this issue and improve the border.
![image](https://user-images.githubusercontent.com/17562139/82058745-bec6a780-96f7-11ea-948a-355f93907b53.png)

**Comment by zer09** [comment]
Thank you so much!
