### ISSUE TITLE
ranger crashes

### ISSUE THREAD

**Issue by monkoose** [kevinhwang91/rnvimr#28]
Self-explained image
![](https://i.imgur.com/bkhhPJa.png?1)

**Comment by kevinhwang91** [comment]
Thanks for your feedback and info. 

I can reproduce by generator a commands.py in ranger config path(`.config/ranger`).

Caused by ranger load `command.py` rather than importing, so inspect couldn't get the module info.

I think this is a fatal issue that prevents new users from trying rnvimr.

**Comment by monkoose** [comment]
Thank You. Works for me now.
