### ISSUE TITLE
Selecting file with ranger doesn't remove [No Name] buffer from buffers list

### ISSUE THREAD

**Issue by monkoose** [kevinhwang91/rnvimr#30]
**How to reproduce:**
- open neovim with `nvim` command. And get scratch `[No Name]` buffer.
- open ranger with rnvimr `:RnvimrToggle`
- open file with `l` and close rnvimr with `q`
` type `:ls` and see that scratch [No Name] buffer still exists.

**Expected behavior:**
`[No Name]` buffer should be removed from buffers list, the same way as it removed if you start editing file with `:e filename.txt` or with selecting file with Netrw (or other fm plugins).

**Comment by kevinhwang91** [comment]
Yes, I can reproduce this issue. It causes by recently committing https://github.com/kevinhwang91/rnvimr/commit/666e2f2d4d362886d4ab736657ce917498581aa4, I am thinking of a good way to solve it.

**Comment by kevinhwang91** [comment]
Fixed!
