### ISSUE TITLE
rnvimr doesn't load more than once

### ISSUE THREAD

**Issue by davis-jordan** [kevinhwang91/rnvimr#36]
When first opening rnvimr, ranger opens properly and works. When I try to open it a second time within nvim, I get this error: 

Error detected while processing function rnvimr#toggle[10]..rnvimr#rpc#attach_file_once[2]..rnvimr#rpc#attach_file[1].
.<SNR>76_valid_setup:
line    2:
ranger has not started yet.
Error detected while processing function rnvimr#toggle[10]..rnvimr#rpc#attach_file_once[2]..rnvimr#rpc#attach_file:
line    3:
E475: Invalid argument: Channel id must be a positive integer

This is the output when I check health:
## Ranger
  - OK: Version: ranger 1.9.3

OS: macOS Catalina

**Comment by kevinhwang91** [comment]
Where is the output? I can't believe only output the message about Ranger.

**Comment by kevinhwang91** [comment]
No reply.
