### ISSUE TITLE
Duplicate tag "g:rnvimr_draw_border" in file /home/kino/.cache/dein/.cache/init.vim/.dein/doc/rnvimr.txt

### ISSUE THREAD

**Issue by cybaol** [kevinhwang91/rnvimr#38]
After I updated the all plugins with dein,
mentioned the following messages,
I don't know waht it means.

**Update started: (2020/07/13 21:59:06)
Error generating helptags:
Vim(helptags):E154: Duplicate tag "g:rnvimr_draw_border" in file /home/kino/.cache/dein/.cache/init.vim/.dein/doc/rnvimr.txt
function <lambda>3[1]..dein#install#_polling[7]..<SNR>113_install_async[9]..<SNR>113_done[9]..dein#install#_recache_runtimepath[19]..
<SNR>113_helptags, line 12
Done: (2020/07/13 21:59:45)**

**Comment by cybaol** [comment]
****

**Comment by kevinhwang91** [comment]
Thanks for your feedback. I use vim-plug which generates tag file silent, so I don't realize the error I made before.
