### ISSUE TITLE
No application knows how to open x

### ISSUE THREAD

**Issue by typkrft** [kevinhwang91/rnvimr#39]
After creating a new file with :touch in Rnvimr it is unable to be opened. This does not happen in running ranger outside of vim. 

Example:
Inside Rnvimr 
`:touch start.vim`
scroll to start.vim and press return
`No application knows how to open start.vim`

Inside Ranger
`:touch start.vim`
scroll to start.vim and press return
Opens in nvim as expected

If I add something to the file so that it is no longer empty Rnvimr opens it in a new buffer as expected. 

I'm not sure what I did as I havent changed my rifle.conf and I ran :rnvimrsync after installing the plug in, but it seems that running the sync again resolved the issue.

**Comment by kevinhwang91** [comment]
Maybe I should give an option to sync config automatically.

**Comment by typkrft** [comment]
> Maybe I should give an option to sync config automatically.

I'm not sure if that's necessary, but if it's easy enough to implement then it probably couldn't hurt. Thanks for the great plugin.

**Comment by kevinhwang91** [comment]
I have released v0.3.0, Rnvimr will import user configuration dynamically.
https://github.com/kevinhwang91/rnvimr/issues/40
