### ISSUE TITLE
Use PlugUpdate cause error msg: 'Post-update hook for rnvimr ... Exit status: 2'

### ISSUE THREAD

**Issue by kevinhwang91** [kevinhwang91/rnvimr#40]
v0.3.0 have removed the Makefile, so use `Plug 'kevinhwang91/rnvimr'` instead of `Plug 'kevinhwang91/rnvimr', {'do': 'make sync'}
`

**Please delete the installed Rnvimr and then reinstall it, because the previously synchronized cache was already in the plugin, Rnvimr will always use cached configuration rather than user configuration.**

Update example:
1. Wrtie `Plug 'kevinhwang91/rnvimr'` to nvim configuration and exit
2. `rm -rf ~/.config/nvim/plugged/rnvimr`
3. Execute `:PlugInstall` in nvim

Get more detail please refer to the CHANGES file.

https://github.com/kevinhwang91/rnvimr/blob/248405f13887c08a4112d8c01d6ed49072b25f5e/CHANGES#L1-L25

**Comment by cybaol** [comment]
U should put Plug 'kevinhwang91/rnvimr'
no need make sync yet

**Comment by monkoose** [comment]
So now you don't need to sync? Or if you have changed ranger config then you need to reinstall rnvimr completely?

**Comment by kevinhwang91** [comment]
> So now you don't need to sync? 

Yes.

> Or if you have changed ranger config then you need to reinstall rnvimr completely?

No, rnvimr will read the user's config path on the fly. 

The old cache produced by `:RnvimrSync` will be always executed in the latest version(v0.3.0), because the cache was inside `ranger/plugins`. The original `lib` path has moved to `ranger/plugins`.

In order to clean the cache inside `ranger` directory, reinstall again for upgrade rnvimr to v0.3.0 is necessary.

**Comment by monkoose** [comment]
Ok, got it. Thank you.

**Comment by kevinhwang91** [comment]
Close this issue because https://github.com/kevinhwang91/rnvimr/issues/50.
