### ISSUE TITLE
Opening a file, it stays inside the small window? Part II

### ISSUE THREAD

**Issue by a-elhag** [kevinhwang91/rnvimr#42]
Same issue as the other gentleman was having: https://github.com/kevinhwang91/rnvimr/issues/23. Everything is working fine, except that any file I open (for example .py) opens inside the pop up window. 

1. Running :checkhealth rnvimr

health#rnvimr#check
```
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

## Pynvim
  - OK: Version: 0.4.1

## Ueberzug (optional)
  - OK: Ueberzug is ready

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```

2. Running a minimal configuration like this will also cause the error:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

**Comment by kevinhwang91** [comment]
I can't reproduce this issue.
1. I'm not sure what your config about `rifle.conf`, so please add `let g:rnvimr_vanilla = 1` to your init.vim, it will make rnvimr use default config for ranger.

2. Do `anyfile` mean all files? It seems that rpc is broken.

**Comment by a-elhag** [comment]
`g:rnvimr_vanilla = 1
`
**This worked perfectly!**

Though I don't know what is wrong with my rifle.conf file, here it is:

[rifle.txt](https://github.com/kevinhwang91/rnvimr/files/5037983/rifle.txt)

**Comment by kevinhwang91** [comment]
```diff
-mime ^text,  label editor = nvim -- "$@"
+mime ^text,  label editor = ${VISUAL:-$EDITOR} -- "$@"
```
rnvimr will replace command of `${VISUAL:-$EDITOR} ` with rpc request.

**Comment by pnchinmay** [comment]
Hi @kevinhwang91 
I've got the same issue even though I used `g:rnvimr_vanilla = 1` in init.vim
Also, the colorschemes for ranger and rnvimr are different
Any help would be appreciated. Thanks
