### ISSUE TITLE
rnvimr_ex_enable not working

### ISSUE THREAD

**Issue by candreslobor** [kevinhwang91/rnvimr#44]
I wanna replace netrw with Ranger, i have set this option in my configs but whenever i open nvim into a folder the manager is the default.

I'm currently using Arch linux.

**Comment by kevinhwang91** [comment]
1. Do the other features work as expected?
2. What does the message output by using `:auto RnvimrFileExplorer` in neovim?
3. try this mini config.
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_enable_ex = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

**Comment by candreslobor** [comment]
> 1. Do the other features work as expected?
Yes.

> 2. What is the message output by using :auto RnvimrFileExplorer in neovim?
`--- Autocommands ---
RnvimrFileExplorer  BufEnter
    *         if isdirectory(expand('<amatch>')) && v:vim_did_enter | bwip
eout! | call rnvimr#open(expand('<amatch>')) | endif`

> 3. try this mini config.
the config didn't work.

**Comment by kevinhwang91** [comment]
1. run `nvim -u ~/mini.vim .`
mini.vim is above snippet.

2. run `nvim +'checkhealth rnvimr'` and post the output.

**Comment by candreslobor** [comment]
> 1. run `nvim -u ~/mini.vim .`
Running the above command didn't work. I currently using the tutorial from [ChrisAtMachine](https://www.youtube.com/watch?v=8qfc7Nqd5hw) i don't know if that config may encounter problems with your plugin

**Comment by kevinhwang91** [comment]
I can't reproduce, and you didn't feedback any useful information.

**Comment by jordanator** [comment]
I had the same issue not being able to replace ranger with netrw on startup, I too followed the tutorial from [ChrisAtMachine](https://www.youtube.com/watch?v=8qfc7Nqd5hw). 

Removing NERDTree resolved the issue for me.

**Comment by kevinhwang91** [comment]
> I had the same issue not being able to replace ranger with netrw on startup, I too followed the tutorial from [ChrisAtMachine](https://www.youtube.com/watch?v=8qfc7Nqd5hw).
> 
> Removing NERDTree resolved the issue for me.

Nice, I forget that people maybe install other file manager plugin such as  [NERDTree](https://github.com/preservim/nerdtree) will cause this issue.
You don't need to uninstall NERDTree, `let g:NERDTreeHijackNetrw = 0` will make it to be compatible with rnvimr.
It should be listed in FAQ.
