### ISSUE TITLE
好像无法读取配置

### ISSUE THREAD

**Issue by XDID** [kevinhwang91/rnvimr#45]
无法读取配置文件, 在使用的时候一直都是默认设置, 也无法在vim中打开文件, 只能在ranger中打开文件

**Comment by kevinhwang91** [comment]
1. 运行`nvim +'checkhealth rnvimr'`并把结果粘贴到这里；

2. 切换到ranger的配置文件目录，Linux下默认是`~/.config/ranger`并运行`tree`，把结果复制到这里；

3. 不介意可以把整个配置目录打包上传到这里好让我重现，谢谢；

**Comment by XDID** [comment]
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - ERROR: Version: 2.7.16 (default, Jul 24 2020, 06:30:38) [GCC Apple LLVM 12.0.0 (clang-1200.0.17.17) [+internal-os]]
    - ADVICE:
      - Python version inside Ranger must be greater than 3
      - Please install Ranger properly

## Pynvim
  - OK: Version: 0.4.1

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - ERROR: RPC: timeout 3s
@kevinhwang91 运行 nvim +'checkhealth rnvimr' 后显示上面的内容

**Comment by kevinhwang91** [comment]
请看readme
>macOS users please install ranger by `pip3 ranger-fm` instead of `brew install ranger`
There're some issues about installation, such as https://github.com/ranger/ranger/issues/1214
Please refer to the issues of ranger for more details
pip3 install ranger-fm pynvim
