### ISSUE TITLE
open file inside rnvimr popup

### ISSUE THREAD

**Issue by HeloSaysHello** [kevinhwang91/rnvimr#47]
So, i was editing some files and decided do add another one, i used :vsplit, opened rnvimr, and selected a file, but instead of opening in nvim, it opened in the popup. It worked normaly a few weeks ago without changing configs. Is there a way to fix this?

**Comment by kevinhwang91** [comment]
How can you produce this issue?

Run `nvim +'checkhealth rnvimr'` and post the output here.

Write `let g:rnvimr_vanilla = 1` into your `init.nvim` and try again, is the issue gone?

**Comment by kevinhwang91** [comment]
no reply.
