### ISSUE TITLE
down with 'j' very slow, while k, arrow-up and arrow-down aren't

### ISSUE THREAD

**Issue by svenXY** [kevinhwang91/rnvimr#48]
Hi,
as the title says, I notice an incredible delay when using `j`to go down, whereas `k`is not a problem, as are `arrow-up`and `arrow-down`

Any ideas?

**Comment by svenXY** [comment]
Does not happen with ranger without nvim.

**Comment by kevinhwang91** [comment]
It seems that your `j` is the prefix key for the terminal remap.

What does `:tmap` say?

**Comment by svenXY** [comment]
you might be right:
```
t  <Esc>       * <C-\><C-N>
t  jk          * <C-\><C-N>
t  <M-y>       * <C-\><C-N>:RnvimrResize 6<CR>
t  <M-l>       * <C-\><C-N>:RnvimrResize 1,8,9,11,5<CR>
t  <M-i>       * <C-\><C-N>:RnvimrResize<CR>
```
I guess the jk is the problem?

**Comment by kevinhwang91** [comment]
Yes, check your vim configuration out.

**Comment by svenXY** [comment]
you are right, that was it, thanks. Can you explain why?

**Comment by kevinhwang91** [comment]
`:help ttimeoutlen`, `:help timeout` and `:help ttimeout` could tell you the reason.
