### ISSUE TITLE
Mac Issue

### ISSUE THREAD

**Issue by haha405pan** [kevinhwang91/rnvimr#49]
hi, 

Thanks for your wonderful plugin, however, I've got some issue and wish you could help me to figure out. 

I have sucessfully install it via vim-plug and health-check was fine. But floating window just won't show up and user configuration of ranger was not imported correctly.

It seems likes this plugin is using bash instead of zsh, which is one that I am currently using. For you information, I can run ranger in my Iterm2 terminal without any problem.

My configuration and screen shot are as follow:
- Mac
- Iterm2
- zsh
-neovim
![Screen Shot 2020-09-24 at 6 31 17 AM](https://user-images.githubusercontent.com/55605373/94081391-9b440400-fe31-11ea-81b8-3c63c60ddbd9.png)

Best regards,
Peter

**Comment by kevinhwang91** [comment]
try this mini config.
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_enable_ex = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```
Is the issue gone?

Btw, I can't get any points what you say about bash, rnvimr hasn't used any bash script. I'm also using zsh.

**Comment by haha405pan** [comment]
> try this mini config.
> 
> ```viml
> call plug#begin('~/.config/nvim/plugged')
> Plug 'kevinhwang91/rnvimr'
> let g:rnvimr_enable_ex = 1
> tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
> nnoremap <silent> <M-o> :RnvimrToggle<CR>
> tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
> call plug#end()
> ```
> 
> Is the issue gone?
> 
> Btw, I can't get any points you say about bash, rnvimr hasn't used any bash script. I'm also using zsh.

Dear Mr.Wang,

Thanks for your swift reply. 
I followed your instruction but somehow broke my Neovim so I reinstall Neovim and plugins. It works fine now. 
I am a newbie. Please bear with me asking stupid question.

Have a good day!

Best regards,
Peter
