### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by kevinhwang91** [kevinhwang91/rnvimr#50]
https://github.com/github/renaming
`vim-plug` support updating repo from the default branch for now.

How to update rnvimr from `main` branch?

1. Run `:PlugUpgrade` to upgrade vim-plug;
2. Delete old rnvimr repo;
3. Run `:PlugInstall` to install rnivmr again;

> Install rnvimr by ~~Plug 'kevinhwang91/rnvimr', {'do': 'make sync'}~~  `Plug 'kevinhwang91/rnvimr'`.

**Comment by theniceboy** [comment]
毫无必要。BLM连github都不放过。都是民主党花的钱。
