### ISSUE TITLE
A file which has been touched within rnvimr does not open in nvim and opens in the browser instead

### ISSUE THREAD

**Issue by serhez** [kevinhwang91/rnvimr#51]
- `nvim --version`: NVIM v0.4.4
- Operating system/version: Linux 5.8.5-arch1-1
- `nvim +'checkhealth rnvimr'`: All OK

**Describe the bug**
When within rnvimr, if you touch a file and then try to open it (with enter or l), it is opened outside nvim. In my case, rnvimr attempts to open the file in Chromium.

**Steps to reproduce the behavior:**
1. Open nvim and rnvimr.
2. Send the command "touch test" to rnvimr.
3. Open the newly created "test" file from rnvimr using enter or l.

**Expected behavior**
The file should open within nvim, as all other files do.

**Screenshots**
Not really valuable, but do let me know if you need them.

**Comment by serhez** [comment]
I fixed it. 

In rifle.conf, comment the lines "label open [...]" and add the following one:

`` label open = ${VISUAL:-$EDITOR} -- "$@" ``

You need to have $VISUAL and $EDITOR set up in .profile or wherever you do that at. Otherwise, just use your normal editor (e.g.: nvim).

This may have unintended consequences, so do it at you own risk (it would try to open any kind of file within your editor, I believe).

I hope this can help others too.

Cheers!

**Comment by kevinhwang91** [comment]
Well done, but this issue has been list in FAQ.
https://github.com/kevinhwang91/rnvimr#faq
