### ISSUE TITLE
Modal window background color

### ISSUE THREAD

**Issue by radutomy** [kevinhwang91/rnvimr#54]
First of all great work, love it!
Not sure if this is a problem with the plugin itself, but I don't get a distinction between the modal window itself and the background. Any idea how to fix this?

L.E: don't know if this matters - I'm SSH'ing into a Ubuntu 20.04 computer from Windows Terminal.

![image](https://user-images.githubusercontent.com/454451/99320696-1b03b300-2864-11eb-93c2-1a90d043cd6d.png)

**Comment by kevinhwang91** [comment]
It seems that your terminal can't render curses chars.

```python
# /usr/bin/env python3

import curses

screen = curses.initscr()
curses.start_color()
curses.init_pair(1, curses.COLOR_BLACK, curses.COLOR_WHITE)
highlightText = curses.color_pair(1)
normalText = curses.A_NORMAL

curses.noecho()
curses.cbreak()
curses.curs_set(0)
screen.keypad(1)
screen.addstr(2, 2, "Screen Resize Test")


def main_screen():
    escape = False
    while escape == False:
        maxY, maxX = screen.getmaxyx()
        screen.attrset(curses.A_NORMAL | highlightText)
        screen.border(curses.ACS_VLINE, curses.ACS_VLINE, curses.ACS_HLINE,
                      curses.ACS_HLINE, curses.ACS_ULCORNER, curses.ACS_URCORNER,
                      curses.ACS_LLCORNER, curses.ACS_LRCORNER)
        screen.addstr(4, 2, "MaxY: " + str(maxY))
        screen.addstr(5, 2, "MaxX: " + str(maxX))

        x = screen.getch()

        if x == ord("q"):
            escape = True
            curses.endwin()
        elif x == curses.KEY_RESIZE:
            screen.erase()
            screen.addstr(2, 2, "Screen Resize Test", curses.A_UNDERLINE)


main_screen()
```

Run the above demo script to run curses tui and check out whether the tui is similar to the below image:
![image](https://user-images.githubusercontent.com/17562139/99383796-5dcb9680-2909-11eb-8baf-3bae7a08671d.png)

There is a workaround to avoid the problem by `let g:rnvimr_draw_border = 0`

**Comment by radutomy** [comment]
Thank you lots. I had `sudo apt ranger` installed and thought that was enough. I had to install the `Pip` version  as per your README to get it to work properly.
