### ISSUE TITLE
Feature: Change working directory from ranger, similar to "NERDTreeMapChdir"

### ISSUE THREAD

**Issue by maximilianigl** [kevinhwang91/rnvimr#55]
Thanks for the great plugin!

One feature that would be great would be to change vim's working directory from within ranger, similar to "NERDTReeMapChdir".

I.e. when executing a certain key on a file or folder within ranger, it doesn't yanks the currently selected path (like 'yw'), but changes the current working directory of vim to that path.

**Comment by kevinhwang91** [comment]
I guess you misunderstand `yw` in ranger. It’ an extra command in rnvimr, which will emit cwd of ranger to nvim’s. `gw` is also an extra command for rnvimr.

`yw` is what you want.

**Comment by maximilianigl** [comment]
Yes, I did misunderstand it. I thought I tried it out, but apparently, I made a mistake :).
Sorry about that and thanks for your help!
