### ISSUE TITLE
Opening within the nested window

### ISSUE THREAD

**Issue by samuelj123** [kevinhwang91/rnvimr#57]
I'm unable to open the file on a new buffer in my nvim session, like it shows in the gif. Pressing 'l' or <Enter> opens another nvim session within the floating window.

![screenshot_026](https://user-images.githubusercontent.com/28726139/101479129-b1b12480-3977-11eb-9483-7cb75b318898.png)

**Comment by keithkeekw** [comment]
I am having the same thing as well. Even though I have edit the rifle.conf file as mentioned in the README.

**Comment by kevinhwang91** [comment]
Please follow the template of bug report to give me infomation.

**Comment by keithkeekw** [comment]
Hi @samuelj123 , you can add `let g:rnvimr_vanilla = 1` into your config.

**Comment by samuelj123** [comment]
That really did the trick! Thanks a lot! @keithkeekw
Much appreciated!

**Comment by keithkeekw** [comment]
@samuelj123 You're welcome!

**Comment by kevinhwang91** [comment]
`let g:rnvimr_vanilla = 1` will disable your config(`rifle.conf` and `rc.conf`), please check out `rifle.conf`, opening file need `${VISUAL:-$EDITOR} -- "$@"`.

**Comment by keithkeekw** [comment]
@kevinhwang91 Noted on that. I only use Ranger in Vim.

**Comment by kevinhwang91** [comment]
> @kevinhwang91 Noted on that. I only use Ranger in Vim.

Off-topic, I use ranger as a hub or context of the file in my system. Combining with [z.lua](https://github.com/skywind3000/z.lua), ranger will be easy to change directory. Inside neovim, ranger is a bridge for me to navigate the directory and edit files.

If you just wanna a TUI file manager, maybe [lf](https://github.com/gokcehan/lf) is your better choice.

Here's my ranger plugin: [plugins](https://github.com/kevinhwang91/dotfiles/tree/main/ranger/plugins).

**Comment by keithkeekw** [comment]
_Just a note for those might having the same issue_
Check the rifle.conf for ranger and ensure that **${VISUAL: $EDITOR} -- "$@"** is present.

Below screenshot is my mistake where I amended it to nvim hence I face the issue:
![Screenshot from 2020-12-09 21-07-53](https://user-images.githubusercontent.com/11871040/101633909-e8b03480-3a62-11eb-93b6-cdf074ce64fa.png)

**Comment by keithkeekw** [comment]
> `let g:rnvimr_vanilla = 1` will disable your config(`rifle.conf` and `rc.conf`), please check out `rifle.conf`, opening file need `${VISUAL:-$EDITOR} -- "$@"`.

Indeed this is the culprit for my case. 

Attached screenshot below for reference:
![Screenshot from 2020-12-09 21-07-53](https://user-images.githubusercontent.com/11871040/101634591-e39fb500-3a63-11eb-8c00-bd644068de71.png)

**Comment by kevinhwang91** [comment]
> > `let g:rnvimr_vanilla = 1` will disable your config(`rifle.conf` and `rc.conf`), please check out `rifle.conf`, opening file need `${VISUAL:-$EDITOR} -- "$@"`.
> 
> Indeed this is the culprit for my case.
> 
> Attached screenshot below for reference:
> ![Screenshot from 2020-12-09 21-07-53](https://user-images.githubusercontent.com/11871040/101634591-e39fb500-3a63-11eb-8c00-bd644068de71.png)

Yes, someone has encountered this issue, I should add it to FAQ latter.

**Comment by samuelj123** [comment]
So basically, I should make sure that wherever it says 'label editor' in my rifle.conf, I should change what's after the = sign to `${VISUAL:-$EDITOR} -- "$@"`
something along the lines of 
`:g/label editor/s/=.*/={$VISUAL:-$EDITOR} -- "$@"`
didn't work for me. Am I missing something?

**Comment by kevinhwang91** [comment]
You just make sure that `label editor = ${VISUAL:-$EDITOR} -- "$@"`, ranger open file is based on `rifle.conf`. rnvimr will match this string and return nonsense `true` command and let neovim open file via rpc.
https://github.com/kevinhwang91/rnvimr/blob/6652fa046fd256243cdffd09d7ecf04965370479/ranger/plugins/patch/rifle.py#L14-L19

**Comment by gadepall** [comment]
I still have the problem in Mac OS

![Image](https://github.com/user-attachments/assets/157bc301-e3ac-4645-8067-db2e18707e02)
