### ISSUE TITLE
Scrolling within rnvimr floating window

### ISSUE THREAD

**Issue by fhill2** [kevinhwang91/rnvimr#58]
Is scrolling files/directories using mouse wheel implemented/working from within the rnvimr floating window?

**Comment by kevinhwang91** [comment]
Are you running nvim with tmux? When the option `mouse=` is the default value, I can scroll in ranger inside nvim, but can't inside nvim with tmux.

**Comment by kevinhwang91** [comment]
I have no idea how to solve this issue about tmux, but I have a workaround, add below script in your config:
```vim
function s:set_mouse_with_tmux() abort
    let n_mouse = &mouse
    if match(n_mouse, '[a|h|n]') < 0 && exists('$TMUX')
        if system('tmux display -p "#{mouse}"')[0]
            augroup RnvimrTmux
                autocmd!
                autocmd FileType rnvimr call <SID>set_mouse_with_tmux()
                autocmd TermEnter,WinEnter <buffer> call system('tmux set mouse off')
                autocmd WinLeave <buffer> call system('tmux set mouse on')
            augroup END
        endif
    endif
endfunction

augroup RnvimrTmux
    autocmd FileType rnvimr call <SID>set_mouse_with_tmux()
augroup END

```

**Comment by fhill2** [comment]
I am not using Tmux.

Posting again for anyone else having issues with Mouse Scrolling inside Rnvimr, as the function provided by @kevinhwang91 has fixed the problem on my system.

The problem for me was starting neovim with `set mouse=a` and opening Rnvimr, scrolling with the mouse wheel scrolled the whole floating window and not the individual folder list inside ranger.

Including the above config to init.vim enabled mouse scrolling of the ranger folder/file list while still being able to use `set mouse=a`

**Comment by kevinhwang91** [comment]
Thank you let me know this script works for you, although it's a bit late, it's better to be late than never.

**Comment by Zeioth** [comment]
@kevinhwang91 your code works as expected. Why not merging it?

I ported it to lua for my settings. But it is your code.

```lua
-- 16. Ranger rnvim enable mouse support
local rnvimr_mouse_group = augroup("RnvimrMouse", { clear = true })

-- Enables mouse support for rnvimr
function set_mouse_with_rnvimr()
  local n_mouse = vim.o.mouse

  -- Disable nvim mouse support while we are on the rnvimr buffer
  if string.match(n_mouse, '[a|h|n]') then
    autocmd({ "TermEnter", "WinEnter <buffer>" }, {
      desc = "Disable nvim mouse support while we are on the rnvimr buffer",
      group = rnvimr_mouse_group,
      callback = function()
       vim.api.nvim_set_option('mouse', '')
      end
    })
  end

  -- Extra mouse fix for tmux
  -- If tmux mouse mode is enabled
  local output = vim.fn.system('tmux display -p "#{mouse}"')
  if output:sub(1, 1) == "1" then

    -- Disable tmux mouse while using rnvimr 
    autocmd({ "TermEnter", "WinEnter <buffer>" }, {
      desc = "Disable tmux mouse while using rnvimr",
      group = rnvimr_mouse_group,
      callback = function()
       vim.fn.system('tmux set mouse off')
      end
    })

    -- Enable tmux mouse when mouse leaves rnvimr
    autocmd({ "WinLeave"}, {
      desc = "Enable tmux mouse when mouse leaves rnvimr",
      group = rnvimr_mouse_group,
      callback = function()
       vim.fn.system('tmux set mouse off')
      end
    })

  end
end

-- Entry point
autocmd({ "FileType rnvimr" }, {
  desc = "If we are on the rnvimr buffer, execute the callback",
  group = rnvimr_mouse_group,
  callback = function()
    -- call function
    set_mouse_with_rnvimr()
  end,
})

```

**Comment by Zeioth** [comment]
But for some weird reason there is a bug where

    autocmd({ "FileType rnvimr" }

Always kicks in no matter what the FileType is. Causing the mouse to be disabled on normal buffers.

**Comment by kevinhwang91** [comment]
> @kevinhwang91 your code works as expected. Why not merging it? I tested it both on foot terminal and then on foot terminal+tmux.

Thanks to remind me for this idea. At the time of opening this issue, the `mouse` option is empty by default. I will merge this script into rnvimr if it works fine for me.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/rnvimr/pull/150
