### ISSUE TITLE
Error in Action: RnvimrSync

### ISSUE THREAD

**Issue by Innei** [kevinhwang91/rnvimr#6]
platform: macOS 10.15.2
![image](https://user-images.githubusercontent.com/41265413/75034285-dbcc4f80-54e7-11ea-9c3d-3bcf14c34002.png)

**Comment by kevinhwang91** [comment]
I am using ArchLinux, it seems that the issue caused by `install` command in macos.

**Comment by kevinhwang91** [comment]
Could you install `coreutils` and try again? I will make the makefile compatible with mac in the future.

**Comment by Innei** [comment]
also can't work. and this plugin write in python3 or python2?

**Comment by kevinhwang91** [comment]
It depends on your system. The plugin only has a single python bin `#!/usr/bin/env python
`. The other lib just plugins of ranger. You should run `ranger --version` to check it out.

Anyway, the version of python is not the point of this issue.

**Comment by kevinhwang91** [comment]
If you want to try this plugin, you can manually copy the lib to the directory `$HOME/.config/nvim/plugged/rnvimr/ranger`. You'd better review the code of `Makefile`.

**Comment by kevinhwang91** [comment]
I have created the branch named 'compatible-with-mac', could you switch branch for testing?
If you using vim-plug, you can add this line to your init.vim
`Plug 'kevinhwang91/rnvimr', {'do': 'make sync', 'branch': 'compatible-with-mac'}`
If this patch works, I will merge it to the master branch.

**Comment by Innei** [comment]
When open file,
![image](https://user-images.githubusercontent.com/41265413/75083178-53cf5f80-5552-11ea-9f53-7a433553973b.png)

and exec `:RnvimrSync` no more errors, but no reaction now.

**Comment by Innei** [comment]
> It depends on your system. The plugin only has a single python bin `#!/usr/bin/env python `. The other libs are just plugins of ranger. You should run `ranger --version` to check it out.
> 
> My env is python3. Anyway, the version of python is not the point of this issue.

```
innei at Inneis-MacBook-Pro.local in [~]
9:18:55 › ranger --version
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Nov  9 2019, 05:55:08) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
Locale: None.None
```

**Comment by kevinhwang91** [comment]
How about run ranger outside neovim? Could you change to python 3 and try again?
I found that I wrote a lot of python 3 syntaxes in the code. I will update the readme required python3.

**Comment by Innei** [comment]
OK, it work. I remove `ranger` which installed by `brew`, this ranger build with python2.

I clone the ranger repo and re-build with python3, now it worked, thank you.

**Comment by kevinhwang91** [comment]
The branch of `compatible-with-mac` already merged into master.

**Comment by Jayphen** [comment]
FYI I had an issue setting this up on my Mac as well.

I am using pyenv, with python 3.7.7 set as my global python version.

I initially installed ranger with homebrew, and it didn't work with this plugin.

After removing and installing with `pip install ranger-fm`, it works.
