### ISSUE TITLE
Rendered picture is still on the screen after exiting rnvimr

### ISSUE THREAD

**Issue by kanglcn** [kevinhwang91/rnvimr#62]
- `nvim --version`:v0.4.4
- Operating system/version: 5.8.18-1-MANJARO
- `nvim +'checkhealth rnvimr'`: 
```
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger-master 

## Python
  - OK: Version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]

## Pynvim
  - OK: Version: 0.4.2

## Ueberzug (optional)
  - OK: Ueberzug is ready

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"


```
**Describe the bug**

Ranger rendered picture still on the screen after exiting rnvimr

1. open nvim using `nvim`
2. toggle rnvimr
3. using ranger browsing and previewing your images
4. toggle rnvimr

**Expected behavior**
The rendered image should also be closed after toggle rnvimr

**Screenshots**
<img width="510" alt="image" src="https://user-images.githubusercontent.com/62387227/103148518-844bdf80-479b-11eb-8133-644151af0137.png">

**Comment by kevinhwang91** [comment]
Thanks for your feedback, I'm knowing this issue, but not sure someone cares about this. I will fix it later.

**Comment by kevinhwang91** [comment]
Update the plugin will fix the issue.

**Comment by kanglcn** [comment]
Thank you for your so quick response!
I also think it's not a big deal. But there are always completists like me ha ha.
