### ISSUE TITLE
Custom Filetype for ranger buffer

### ISSUE THREAD

**Issue by Chaitanyabsprip** [kevinhwang91/rnvimr#66]
**Is your feature request related to a problem? Please describe.**
I have `jk` and `kj` bound to escape into normal mode for terminal mode and insert mode. As Ranger works in terminal mode this adds a delay when I am browsing files. 

**Describe the solution you'd like**
If the terminal buffer in which ranger is working will have a custom filetype or some indentification it will be easy to make custom and conditional key bindings for ranger in nvim.

**Comment by kevinhwang91** [comment]
After creating the ranger buffer, rnvimr will `set ft=rnvimr`, I think you can remap key for the escape key for terminal mode.

**Comment by Chaitanyabsprip** [comment]
```
autocmd Filetype rnvimr inoremap jk <nop>
autocmd Filetype rnvimr inoremap kj <nop>
autocmd Filetype rnvimr tnoremap jk <nop>
autocmd Filetype rnvimr tnoremap kj <nop>
``` 
these commands should work but aren't.

**Comment by kevinhwang91** [comment]
```vim
autocmd Filetype rnvimr tnoremap <buffer><nowait> j j
autocmd Filetype rnvimr tnoremap <buffer><nowait> k k
```

**Comment by Chaitanyabsprip** [comment]
I tried the mappings you suggested and those are not working as required. It doesn't seem to be doing anything, I get an error message saying the mapping doesn't exist

**Comment by kevinhwang91** [comment]
What does `:tmap` say in rnvimr? Before pressing `:tmap`, make sure that you are at normal mode in rnvimr buffer.

**Comment by Chaitanyabsprip** [comment]
```t  <Esc>       * <C-\><C-N>                                                                                                                                                
t  jk          * <C-\><C-N>
t  kj          * <C-\><C-N>
t  <M-o>       * <C-\><C-N>:RnvimrToggle<CR>
t  <M-i>       * <C-\><C-N>:RnvimrResize<CR>
t  <M-[>       * <C-\><C-N>
```

**Comment by kevinhwang91** [comment]
> ```viml
> autocmd Filetype rnvimr tnoremap <buffer><nowait> j j
> autocmd Filetype rnvimr tnoremap <buffer><nowait> k k
> ```

The above snippet work for me, please add it into your init.vim. Or run them before ranger started.

**Comment by Chaitanyabsprip** [comment]
``` 
vim.api.nvim_set_keymap('t', 'jk', '<c-\\><c-n>', {noremap=true, silent=true})
vim.api.nvim_set_keymap('t', 'kj', '<c-\\><c-n>', {noremap=true, silent=true})
```
This is how I've set the keymap
```
augroup ranger
    autocmd! Filetype rnvimr tnoremap <buffer><nowait> j j
    autocmd! Filetype rnvimr tnoremap <buffer><nowait> k k
augroup end
```
and this is how I used your snippet
and it is not working, when I open ranger an error message pops saying `Error detected while processing FileType Autocommands for "rnvimr":  E31: No such mapping`

**Comment by kevinhwang91** [comment]
```vim
augroup ranger
    au!
    autocmd Filetype rnvimr tnoremap <buffer><nowait> j j
    autocmd Filetype rnvimr tnoremap <buffer><nowait> k k
augroup end
```

**Comment by Chaitanyabsprip** [comment]
works now, thank you.
