### ISSUE TITLE
`set termguicolors` causes rnvimr to display incorrect colors

### ISSUE THREAD

**Issue by AkashKarnatak** [kevinhwang91/rnvimr#67]
nvim-version - 0.4.4
OS - Debian Buster
Terminal - Konsole
Terminal theme - Monokai

`rnvimr` does not use same colors as `ranger` after adding this line `set termguicolors` to `init.vim`.

Ranger in terminal

![Screenshot from 2021-01-07 02-03-15](https://user-images.githubusercontent.com/54985621/103820017-8a8e6580-5091-11eb-8db7-7deab809b7f8.png)

Ranger inside neovim

![Screenshot from 2021-01-07 02-03-30](https://user-images.githubusercontent.com/54985621/103820081-ab56bb00-5091-11eb-9eab-2035f4e65220.png)

**Comment by kevinhwang91** [comment]
0.4.4 nvim don't support terminal base 16 color them, there are two ways to make ranger more sexy inside neovim:
1. manual set terminal colors like `let g:terminal_color_4 = '#ff0000'`, you can run `:help terminal-config` for more details;
2. upgrade neovim to 0.5 version, and make sure `g:terminal_color_x` is undefined.
