### ISSUE TITLE
RPC: timeout 3s, error install python 3 or higher even though i already had it

### ISSUE THREAD

**Issue by auliamnaufal** [kevinhwang91/rnvimr#68]
- `nvim --version`: NVIM v0.4.4
- Operating system/version: Macos 11.0.1
- `nvim +'checkhealth rnvimr'`: 
```
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - ERROR: Version: 2.7.16 (default, Oct 30 2020, 02:15:49) [GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri
    - ADVICE:
      - Python version inside Ranger must be greater than 3
      - Please install Ranger properly

## Pynvim
  - OK: Version: 0.4.2

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - ERROR: RPC: timeout 3s
```

**Describe the bug**
`init.vim`
```
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/themes/onedark.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/plug-config/fzf.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/plug-config/rnvimr.vim
```

`plugins.vim`
```
    "Ranger
    Plug 'kevinhwang91/rnvimr'
```

`rnvmir.vim`
```
" Make Ranger replace netrw and be the file explorer
let g:rnvimr_ex_enable = 1

nmap <space>r :RnvimrToggle<CR>
```

`rc.conf`
```
set preview_images_method ueberzug

default_linemode devicons

set show_hidden true
```

so The problem is the rmvmir does not show hidden file not as i configure it at the rc.conf but everything else does work like the buffer for the rmvimr shows up when i toggle it

1. :RvimrToggle
2. </(space)>R
3.

**Expected behavior**
1. Show hidden file, the same ass the ranger command

**Screenshots**
From `ranger` command on terminal
<img width="1552" alt="Screen Shot 2021-01-08 at 12 06 42" src="https://user-images.githubusercontent.com/60921990/103976674-f9f77880-51a9-11eb-863d-58a181941a85.png">

From `:RmvmirToggle` inside nvim
<img width="1552" alt="Screen Shot 2021-01-08 at 12 07 27" src="https://user-images.githubusercontent.com/60921990/103976710-14c9ed00-51aa-11eb-9fec-6366e2d5382f.png">

**Additional context**
i already have python 3 installed on my machine. perhaps i have to configure it?

**Comment by kevinhwang91** [comment]
Install ranger via `pip` instead of brew in macOS, readme has already reminded it.
