### ISSUE TITLE
In and out left border

### ISSUE THREAD

**Issue by yanzhang0219** [kevinhwang91/rnvimr#69]
Hello, 

The left border is in and out (i.e., disappearing and reappearing) when I navigate back and force. I attached a short video below.

https://user-images.githubusercontent.com/11582667/105309790-e537bf00-5b71-11eb-9dd8-cbfa000c022a.mov

My system info:
* macOS: Big Sur 11.1
* nvim: NVIM v0.5.0-4875db2
* ranger: the latest, i.e., built from the latest master. In addition, I already checked the output of `pip3 list` and it showed `ranger-fm` and `pynvim` were installed. 

I am not sure whether this is a bug or I miss something?
Thank you very much. 

Update:
I found this issue only happens when I first launch rnvimr. I launch rnvimr using `:RnvimrToggle`, and then I press `q` to quit it. When I re-launch it again, the left border has a correct display.

**Comment by kevinhwang91** [comment]
Thanks for the feedback, I can reproduce the issue in Big Sur 11.1.

But the issue can't be reproduced in Linux, I'm afraid it's an issue about lib of python, but I will fix it as I could.

**Comment by yanzhang0219** [comment]
Thank you. One more thing, after I launch it via `:RnvimrToggle`, I use `<C-\><C-n>` to exit the terminal mode, and then I execute `:RnvimrResize`, the terminal window becomes a little larger and this issue is gone.

**Comment by kevinhwang91** [comment]
After logging compares with Linux, I found that this issue is caused by ranger in macOS can't receive a resize signal.

It absolutely could be fixed, I want to find an appropriate workaround.

**Comment by kevinhwang91** [comment]
After logging compares with Linux, I found that this issue is caused by ranger in macOS can't receive a resize signal.

It absolutely could be fixed, I want to find an appropriate workaround.

**Comment by yanzhang0219** [comment]
Awesome. Thank you. It is definitely a nice ranger plugin. ❤️

**Comment by kevinhwang91** [comment]
I think the issue is fixed. If you have another issue, feedback is welcome.

**Comment by yanzhang0219** [comment]
Great! Thanks agian.
