### ISSUE TITLE
Have the option to keep Ranger open even with `let g:rnvimr_enable_picker = 1`

### ISSUE THREAD

**Issue by galou** [kevinhwang91/rnvimr#72]
**Is your feature request related to a problem? Please describe.**
Most of the time, I want to close ranger when opening a file, so I set `let g:rnvimr_enable_picker = 1` but sometimes, I'd like to keep it open.

**Describe the solution you'd like**
The solution I tried and I'd like is:
```vim
let g:rnvimr_action = {
            \ '<C-o>': 'NvimEdit edit'
            \ }
```
but it doesn't work as I expect, the file does open but ranger get hidden.

**Comment by kevinhwang91** [comment]
```vim
let g:rnvimr_action = {
            \ '<C-o>': 'NvimEdit edit False'
            \ }
```
Documents will be supplemented later

**Comment by galou** [comment]
Woah! That was quick! Thanks!
