### ISSUE TITLE
不能使用nvim打开文件夹，[Process exited 134]

### ISSUE THREAD

**Issue by 10ve** [kevinhwang91/rnvimr#73]
- `nvim --version`:
```
NVIM v0.5.0-dev+cc1851c9f
Build type: Release
LuaJIT 2.1.0-beta3
```
- Operating system/version:
`Darwin yangdeMBP 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`
- `nvim +'checkhealth rnvimr'`: 
```
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.1 (default, Jan  8 2021, 17:17:43) [Clang 12.0.0 (clang-1200.0.32.28)]

## Pynvim
  - OK: Version: 0.4.2

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"

```
**Describe the bug**
let g:rnvimr_enable_ex = 1
nvim不能打开文件夹文件夹 
[Process exited 134]

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.local/share/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_enable_ex = 1
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

1.let g:rnvimr_enable_ex = 1
2.使用nvim打开文件夹
3.[Process exited 134]

**Expected behavior**
正常打开文件夹

**Screenshots**
<img width="639" alt="截屏2021-02-03 下午4 59 26" src="https://user-images.githubusercontent.com/11514850/106722659-2e434500-6641-11eb-9eb7-c1e975f6bed2.png">

**Comment by kevinhwang91** [comment]
谢谢反馈，你这更新nvim太频繁快了吧，是https://github.com/neovim/neovim/commit/ef7c6b972a1100fc5b173b7273f2c29017557669引起的，我看看怎么解决：）

**Comment by kevinhwang91** [comment]
上游bug，已经提了issue: https://github.com/neovim/neovim/issues/13874
我有办法解决规避这个问题，但还是等几天看看上游的态度吧：）

**Comment by kevinhwang91** [comment]
上游有意愿修复，并且已经提交PR，我测试了是可以的，等着合并吧：）
