### ISSUE TITLE
Invalid linemode: devicons

### ISSUE THREAD

**Issue by taoliv** [kevinhwang91/rnvimr#74]
- `nvim --version`: 0.4.4
- Operating system/version: 5.9.16-1-MANJARO
- `nvim +'checkhealth rnvimr'`: 
```
 init.vim  [No Name]                                                                                                                                                                         X
    1
    2 health#rnvimr#check
    3 ========================================================================
    4 ## OS
    5   - OK: Name: Linux
    6
    7 ## Ranger
    8   - OK: Version: ranger 1.9.3
    9
   10 ## Python
   11   - OK: Version: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
   12
   13 ## Pynvim
   14   - OK: Version: 0.4.2
   15
   16 ## Ueberzug (optional)
   17   - OK: Ueberzug is ready
   18
   19 ## RPC
   20   - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
   21
```
**Describe the bug**
Can not display devicons. 
And it reports an error: "loading...**rangerInvalid linemode: devicons**; should be filename/metatitle/...".

**My configuration**

```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr', { 'on': 'RnvimrToggle' }
call plug#end()

let g:rnvimr_enable_ex = 1
let g:rnvimr_enable_picker = 1
let g:rnvimr_enable_bw = 1
```

**Expected behavior**
In my ranger:
![image](https://user-images.githubusercontent.com/54020696/107739697-6e42b000-6d44-11eb-8322-e37ff83c212a.png)

**Screenshots**
When open ranger in nvim:
![image](https://user-images.githubusercontent.com/54020696/107739512-012f1a80-6d44-11eb-8e6d-899a6ac4e7ed.png)

**Comment by kevinhwang91** [comment]
Please provide the message  `tree ~/.config/ranger` and follow the https://github.com/alexanderjeurissen/ranger_devicons#install-instructions steps

**Comment by taoliv** [comment]
Thanks for your reply. I just figured it out.
My directory structure just now is:

```shell
tree ~/.config/ranger/plugins
.
├── compress.py
├── devicons.py
├── extract.py
└── __init__.py

0 directories, 4 files
```
`__init__.py` and  `devicons.py` are copied from https://github.com/alexanderjeurissen/ranger_devicons.

When I create a subfolder `devicons` here and move `__init__.py` and  `devicons.py` to `devicons`, it works:
```shell
tree ~/.config/ranger/plugins
.
├── compress.py
├── devicons
│   ├── devicons.py
│   ├── __init__.py
│   └── __pycache__
│       ├── devicons.cpython-38.pyc
│       └── __init__.cpython-38.pyc
├── extract.py
└── __pycache__
    ├── compress.cpython-38.pyc
    ├── devicons.cpython-38.pyc
    ├── extract.cpython-38.pyc
    └── __init__.cpython-38.pyc

3 directories, 10 files
```
