### ISSUE TITLE
Change default on enter behaviour

### ISSUE THREAD

**Issue by fazibear** [kevinhwang91/rnvimr#75]
How can I change default on enter behaviour. I can press `ctl-t`  to open file in new tab, but I want to make enter open file in new tab.  It it possible to configure plugin like this?

**Comment by kevinhwang91** [comment]
```vim
let g:rnvimr_action = {
            \ '<CR>': 'NvimEdit tabedit'
            \ }
```
`:h rnvimr_action` for detail

**Comment by fazibear** [comment]
Is there an option to switch to existing tab if already opened?

**Comment by kevinhwang91** [comment]
`drop` seemly doesn't work in rnvimr, I will fix it later.

**Comment by kevinhwang91** [comment]
update the repo and
```vim
let g:rnvimr_action = {
            \ '<CR>': 'NvimEdit drop'
            \ }
```

**Comment by hamensman** [comment]
How would this be done with `l` key, which - when at a file - also opens it in ranger by default?

Because if I did it like this...
```vim
let g:rnvimr_action = {
            \ 'l': 'NvimEdit drop'
            \ '<CR>': 'NvimEdit drop'
            \ }
```
...then I can't use `l` to navigate around ranger :(

**Comment by kevinhwang91** [comment]
> How would this be done with `l` key, which - when at a file - also opens it in ranger by default?
> 
> Because if I did it like this...
> 
> ```viml
> let g:rnvimr_action = {
>             \ 'l': 'NvimEdit drop',
>             \ '<CR>': 'NvimEdit drop'
>             \ }
> ```
> 
> ...then I can't use `l` to navigate around ranger :(

Upgrade code and  `let g:rnvimr_edit_cmd = 'drop'`

**Comment by hamensman** [comment]
> How would this be done with `l` key, which - when at a file - also opens it in ranger by default?
> 
> Because if I did it like this...
> 
> ```viml
> let g:rnvimr_action = {
>             \ 'l': 'NvimEdit drop',
>             \ '<CR>': 'NvimEdit drop'
>             \ }
> ```
> 
> ...then I can't use `l` to navigate around ranger :(

Sorry, meant this:

```vim
let g:rnvimr_action = {
            \ 'l': 'NvimEdit tabedit',
            \ '<CR>': 'NvimEdit tabedit'
            \ }
```

So I'd want `l` to of course navigate as normal, but also open file in new tab (**instead** of in ranger popup)

**Comment by kevinhwang91** [comment]
> > How would this be done with `l` key, which - when at a file - also opens it in ranger by default?
> > Because if I did it like this...
> > ```viml
> > let g:rnvimr_action = {
> >             \ 'l': 'NvimEdit drop',
> >             \ '<CR>': 'NvimEdit drop'
> >             \ }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...then I can't use `l` to navigate around ranger :(
> 
> Sorry, meant this:
> 
> ```viml
> let g:rnvimr_action = {
>             \ 'l': 'NvimEdit tabedit',
>             \ '<CR>': 'NvimEdit tabedit'
>             \ }
> ```
> 
> So I'd want `l` to of course navigate as normal, but also open file in new tab (**instead** of in ranger popup)

Remove your `g:rnvimr_action`

**Comment by hamensman** [comment]
> Remove your `g:rnvimr_action`

What do I then add instead?
