### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by bechampion** [kevinhwang91/rnvimr#77]
Would you mind sharing that ranger color scheme?

**Comment by kevinhwang91** [comment]
It's my alacritty color.

https://github.com/kevinhwang91/dotfiles/blob/92a8060cbd79336eace018c4fbf78c2283edad67/alacritty/alacritty.yml#L252-L271

BTW,  you should check https://github.com/kevinhwang91/rnvimr/issues/67 first

**Comment by bechampion** [comment]
im struggling to get a bg color difference between the middle column (active one ) and the one on the left ( the not active one) do you know what context woud that be?

**Comment by kevinhwang91** [comment]
It's the default color scheme that is based on your terminal color. `set colorscheme default`

I have no idea how to make the bg of the browse column different.
