### ISSUE TITLE
No longer able to split in the direction of my choosing

### ISSUE THREAD

**Issue by victorchabbert** [kevinhwang91/rnvimr#79]
- `nvim --version`: v0.5.0-dev+0fad952a2
- Operating system/version: MacOS 11 Big Sur
- `nvim +'checkhealth rnvimr'`: 
```
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.2 (default, Mar 26 2021, 23:22:38) [Clang 12.0.0 (clang-1200.0.32.29)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**
When overriding `rnvimr_action`	providing custom keybindings for splits, I'm no long able to split.

**To Reproduce**

1. Provide any split argument like below
2. Split in a direction

Example:
```lua
// Lua
vim.g.rnvimr_action = {
  ['gw'] = 'JumpNvimCwd',
  ['yw'] = 'EmitRangerCwd',
  ['†'] = 'NvimEdit tabedit', -- ALT+t
  ['˙'] = 'NvimEdit leftabove vsplit', -- ALT+h
  ['¬'] = 'NvimEdit rightbelow vsplit', -- ALT+l
  ['˚'] = 'NvimEdit leftabove split', -- ALT+k
  ['∆'] = 'NvimEdit rightbelow split' -- ALT+j
}
```

**Expected behavior**
I can split in the direction of my choice.

**Additional context**
It appears that this commit [8af7dda8](https://github.com/kevinhwang91/rnvimr/commit/8af7dda8ecc2014ac1c62189f5070c8147e9db37#diff-9cab3e6337a867e439b378145839ceff9adf3acecb0ca3e171fb38af10246affL18) changed the behavior.

Let me know if you need additional info.
Thanks

**Comment by kevinhwang91** [comment]
Good bisect, Fixed, Thanks:)
