### ISSUE TITLE
[Feature request] support python3_host_prog

### ISSUE THREAD

**Issue by laggardkernel** [kevinhwang91/rnvimr#82]
`:h python3_host_prog`, I have this global variable set and installed `ranger-fm`, `pynvim` within. But this interpreter is not chosen by rnvimr without activating this very interpreter manually.

**Comment by kevinhwang91** [comment]
OK, so many users complain about it. I will try to implement this feature.

**Comment by kevinhwang91** [comment]
Please try below snippet which works for me.
```vim
let g:python3_host_prog = 'path/python'
let g:rnvimr_ranger_cmd = g:python3_host_prog . ' ' . fnamemodify(g:python3_host_prog,':h') . '/ranger --cmd"=set draw_borders both"'
```

**Comment by laggardkernel** [comment]
Thanks. This does work for me.

```vim
let g:rnvimr_ranger_cmd = fnamemodify(g:python3_host_prog,':h') . '/ranger'
```

Another problem I encountered is that the bookmarks are not listed after typing `'`, even I specify the conf dir with `-r /path/to/my/ranger/conf` in `g:rnvimr_ranger_cmd`. No idea why the bookmarks are lost when using this plugin.

**Comment by kevinhwang91** [comment]
> Thanks. This does work for me.
> 
> ```viml
> let g:rnvimr_ranger_cmd = fnamemodify(g:python3_host_prog,':h') . '/ranger'
> ```
I suggest you run `eval ranger` cmd in ranger to make sure the python interpreter as you expect.

> Another problem I encountered is that the bookmarks are not listed after typing `'`, even I specify the conf dir with `-r /path/to/my/ranger/conf` in `g:rnvimr_ranger_cmd`. No idea why the bookmarks are lost when using this plugin.

I can't reproduce this issue. Please check out your bookmarks file. Here's my path
`~/.local/share/ranger/bookmarks`

**Comment by laggardkernel** [comment]
> I can't reproduce this issue. Please check out your bookmarks file after ranger is exited. Here's my path
> `~/.local/share/ranger/bookmarks`

My bookmark file is `~/.config/ranger/bookmarks`. I did a search of keyword "bookmarks" in my ranger configs. Turns out this place is not a custom location defined by me. It should be a standard place supported by ranger. No idea why it's not preferred over `~/.local/share/ranger/bookmarks` within `rnvimr`, although it takes precedence over the one in `~/.local/share/...` outside neovim. 

I put the bookmarks under `~/.config/ranger` cause I wanna the bookmark file collected to my dotfile. Um, I'll make `~/.local/share/ranger/bookmarks` as a symlink for a temp solution.

> Press `q` in neovim can't actually exit ranger, use `Q` instead.

I prefer <kbd>Meta-o</kbd> to toggle display of ranger, cause `q` also quits a tab.

**Comment by kevinhwang91** [comment]
> My bookmark file is `~/.config/ranger/bookmarks`. I did a search of keyword "bookmarks" in my ranger configs. Turns out this place is not a custom location defined by me. It should be a standard place supported by ranger. No idea why it's not preferred over `~/.local/share/ranger/bookmarks` within `rnvimr`, although it takes precedence over the one in `~/.local/share/...` outside neovim.
> 
> I put the bookmarks under `~/.config/ranger` cause I wanna the bookmark file collected to my dotfile. Um, I'll make `~/.local/share/ranger/bookmarks` as a symlink for a temp solution.

Please check out https://github.com/ranger/ranger/blob/905298d3dcd1fcb3f4c25d88c2584cd2cc46c838/ranger/core/fm.py#L306-L314

This plugin proxy `confdir` load its library and load default `confdir` latter, I think this is a bug for rnvimr, we should change `confdir` after loading default `confdir`. I will fix it later.

**Comment by kevinhwang91** [comment]
@laggardkernel Code is updated, I think you can delete your linked file.
