### ISSUE TITLE
Customize used colors

### ISSUE THREAD

**Issue by JosefLitos** [kevinhwang91/rnvimr#85]
I have looked through the highlighted groups but didn't find anything but RnvimrNormal and RnvimrCurses of which a change didn't seem to do much.
I would like to be able to set all the colors ranger uses, although it seems it somehow changes with my colorscheme, it changes often to very unpleasant color pallete.

**Comment by kevinhwang91** [comment]
Depend on your ranger color schema, what schema do you expect?

**Comment by JosefLitos** [comment]
Oh, It actually might be that I have used just the jungle colorscheme inside ranger so it uses the default colors provided. Anyway, the colors shown are different with any vim colorscheme. If that is the problem, how do I change the colorscheme in ranger itself, I didn't notice a help about loading custom python files to ranger.

**Comment by kevinhwang91** [comment]
You can customize your terminal color schema and make `default` color schema for ranger.
FYI: https://github.com/kevinhwang91/rnvimr/issues/67
