### ISSUE TITLE
How to use rc.conf in rnvimr?

### ISSUE THREAD

**Issue by lsli0116** [kevinhwang91/rnvimr#86]
Hi everyone. I am using `rnvimr `in `neovim` on macOS. I have change my ranger keymapping in `.config/ranger/rc.conf`, but in `rnvimr`, all the modified keys become invalid. So I want to know how I can config to use the configuration in  `.config/ranger/rc.conf`, I have add `let g:rnvimr_urc_path = '$XDG_CONFIG_HOME/ranger` in `nvim/init.vim`, but it doesn't work.

**Comment by kevinhwang91** [comment]
install ranger via pip3. try minimal configuration will work.

**Comment by lsli0116** [comment]
Yes, it works. Really thanks for your reply :)
