### ISSUE TITLE
Ability to change it to use lf instead of ranger

### ISSUE THREAD

**Issue by thepenguinthatwants** [kevinhwang91/rnvimr#87]
As ridiculous as this suggestion sound it makes bit sense, would be nice if I can pipe it to use lf file manager instead of ranger. As it has being proven a lot more stable.

**Comment by kevinhwang91** [comment]
No, because this plugin is base on RPC, lf can't run a server with monkey patch. There're many plugins about lf, you should give them a try. BTW, thanks for opening an issue share your idea.
