### ISSUE TITLE
Support the installed `pynvim` and `ranger` in python virtualenv

### ISSUE THREAD

**Issue by Alienover** [kevinhwang91/rnvimr#88]
**Is your feature request related to a problem? Please describe.**
In setting up NeoVim, I created two python envs for it which are named `neovim_py2` and `neovim_py3`.
And of course, the NeoVim required packages (`neovim`, `pynvim`) are installed on both envs.

If I install the `ranger` outside the env, the RPC would timeout in the health checking. ❌
If I install it in the env, it works great. ✅
But I need to activate the env each time I use `rnvimr`. 

**Describe the solution you'd like**
If I need to use `rnvimr`, I need to activate the env before entering nvim.

**Describe alternatives you've considered**

**Additional context**
I don't know the detail about `rnvimr`. But I think nvim should be able to access the packages which are installed in the env if I set `g:python_host_prog` and `python3_host_prog` properly.

```vim
" Python2 for neovim
if filereadable($HOME.'/.virtualenvs/neovim_py2/bin/python')
    let g:python_host_prog=$HOME.'/.virtualenvs/neovim_py2/bin/python'
endif

" Python3 for neovim
if filereadable($HOME.'/.virtualenvs/neovim_py3/bin/python')
    let g:python3_host_prog=$HOME.'/.virtualenvs/neovim_py3/bin/python'
endif

```
When I execute the command beblow outside the python env, i returns the `site-packages` in the env.
```vim
:py3 import sys; print(sys.prefix); print(); print(sys.path)

" --> $HOME/.virtualenvs/neovim_py3
" --> ['$HOME/.pyenv/versions/3.7.10/lib/python37.zip', '$HOME/.pyenv/versions/3.7.10/lib/python3.7', '$HOME/.pyenv/versions/3.7.10/lib/python3.7/lib-dynload', '$HOME/.virtualenvs/neovim_py3/lib/python3.7/site-packages', '_vim_path_']
```

---
So, I am wondering whether I can install the `ranger` outside the python env and leave the `neovim` and `pynvim` installed in the env.

**Comment by kevinhwang91** [comment]
`let g:rnvimr_ranger_cmd = 'your venv path/bin/ranger'` should work.

**Comment by Max-Tayne** [comment]
For anyone trying to get this working on MacOS having installed python with homebrew and trying to config with lazy...my condolences. The way I got it working was to create a virtual env for python at ~/.venv/neovim, install ranger and pynvim to that with pip3, then use the following to config the plugin: 

```
{
    "kevinhwang91/rnvimr", -- (RNVIMR, Ranger file browser)
    lazy = true,
    init = function()
      vim.g.rnvimr_ranger_cmd = { "/Users/<username>/.venv/neovim/bin/ranger", "--cmd=set draw_borders both" }
      vim.g.rnvimr_enable_picker = 1
      vim.g.rnvimr_enable_ex = 1
      vim.g.rnvimr_enable_bw = 1
      -- Softens windows behind nvimr a bit, 0 = max opaque, 100 is invisible
      vim.g.rnvimr_shadow_winblend = 70
    end,
    keys = {
      { "<leader>r", ":RnvimrToggle<CR>", desc = "Ranger Explorer" },
    },
  },
```

additionally, in my options.lua file, did the following:
```
vim.g.python3_host_prog = vim.fn.expand("~/.venv/neovim/bin/python3")
```
