### ISSUE TITLE
Touch to create a new file and press enter will open the file by OS default editor

### ISSUE THREAD

**Issue by AllenDang** [kevinhwang91/rnvimr#89]
```
NVIM v0.6.0-dev+1518-g02bf251bb
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210714-39663-lqn3eb/build/config -I/tmp/neovim-20210714-39663-lqn3eb/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210714-39663-lqn3eb/build/src/nvim/auto -I/tmp/neovim-20210714-39663-lqn3eb/build/include
编译者 allendang@MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/HEAD-02bf251/share/nvim"

Run :checkhealth for more info
```
**Describe the bug**
1. Open ranger inside neovim
2. `:touch init.go` to create a file named `init.go`
3. Press enter on init.go
4. OS default editor will be launched. 

**Expected behavior**
init.go will be opened by neovim and ranger is closed.

**Comment by kevinhwang91** [comment]
> FAQ
Q: Couldn't open some special types of files by using Enter or l in Ranger.

**Comment by AllenDang** [comment]
@kevinhwang91 Thing is, I could open a existing go file normally by pressing enter. This issue only happens for file just created by touch command.

**Comment by kevinhwang91** [comment]
What is `r` say?

**Comment by AllenDang** [comment]
@kevinhwang91 Here is existing file with `r`
![截屏2021-07-20 下午2 47 33](https://user-images.githubusercontent.com/18550/126274695-5bf400a9-67d8-4a5f-95bf-d8bce882b8b8.png)

Here is newly created file by `:touch` with `r`
![截屏2021-07-20 下午2 47 23](https://user-images.githubusercontent.com/18550/126274767-61fe4f20-9fc7-449c-9335-bd8051677bfc.png)

**Comment by kevinhwang91** [comment]
change your `rifle.conf`
