### ISSUE TITLE
Opening a file opens in external editor

### ISSUE THREAD

**Issue by Jayphen** [kevinhwang91/rnvimr#9]
Thanks for the plugin, I much prefer it to the alternatives.

I have an issue where the plugin will open certain filetypes in an external editor.

I don't have a full list of file extensions that it happens with, but it definitely happens when I try to open a `.ts` file.

**Comment by kevinhwang91** [comment]
It depends on your rifle.conf. You should press `r` to make sure that the `${VISUAL:-$EDITOR} -- "$@"` is the best candidate. rnvimr only change the VISUAL environment to communicate with neovim by RPC.

Someone had messaged me about the case you said above, I think I should write it down in README.

**Comment by kevinhwang91** [comment]
You can change the code under the rifle.conf like that:
```diff
-!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = ${VISUAL:-$EDITOR} -- "$@"
+!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|ts = ${VISUAL:-$EDITOR} -- "$@"
```

**Comment by Jayphen** [comment]
Thanks, adding ts to the list worked. Yes, it would be helpful to mention in the readme!
