### ISSUE TITLE
Integration w/ Other File Managers

### ISSUE THREAD

**Issue by is0n** [kevinhwang91/rnvimr#90]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a bug.

**Describe the solution you'd like**
I would like to be able to configure rnvimr in a way that allows the usage of a different file manager.

Example:
let g:rnvimr_executable = "file manager of choice"

**Describe alternatives you've considered**
Using a floating terminal plugin w/ the file manager of my choice, however, I have found that when I open a file from within a terminal plugin, it opens it in a new instance of neovim (located inside of the terminal) instead of opening a new buffer with the selected file.

I have not found a plugin for neovim that supports the file manager of my choice (that file manager being [joshuto](https://github.com/kamiyaa/joshuto))

**Additional context**
I have attempted to use [nvim-toggleterm.lua](https://github.com/akinsho/nvim-toggleterm.lua) w/ [neovim-remote](https://github.com/mhinz/neovim-remote) and I have only been somewhat successful (view my [issue](https://github.com/akinsho/nvim-toggleterm.lua/issues/66) for more info)

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/rnvimr/issues/87
