### ISSUE TITLE
Opening file throws error when neovim is ran on a directory

### ISSUE THREAD

**Issue by Hunter522** [kevinhwang91/rnvimr#91]
- `nvim --version`:  NVIM v0.5.0
- Operating system/version: Fedora 34
- `nvim +'checkhealth rnvimr'`: 
```
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - WARNING: Ueberzug is not found in Python Lib

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```
**Describe the bug**

When opening a directory with nvim, rnvimr will pop up. But when you try opening up a file when `hidden = true` rnvimr throws an error:

```
Error detected while processing function <lambda>14[1]..<SNR>72_defer_check_dir[3]..rnvimr#open[6]..rnvimr#toggle[13]..<SNR>72_reopen_win:
line    2:
E5555: API call: Invalid buffer id: 3
Press ENTER or type command to continue
```

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/rnvimr'
let g:rnvimr_vanilla = 1
let g:rnvimr_enable_ex = 1
let g:rnvimr_enable_picker = 1
set hidden 
tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR>
nnoremap <silent> <M-o> :RnvimrToggle<CR>
tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR>
call plug#end()
```

1. `nvim -u mini.vim somedirectory`
2. Pick file from ranger popup
3. Observe error

**Expected behavior**
Ranger popup should close/hide when file is picked.

**Additional context**
rnvimr seems to behave correctly with `hidden = true` as long as you dont start neovim on a directory. I've tested this with launching neovim with no arg, launching with file, and launching with session. 

I set `hidden` because I want to use https://github.com/akinsho/nvim-toggleterm.lua. I'm sure `hidden` is useful to other for other reasons.

A workaround for me right now is to just run `neovim` with no args then toggle rnvimr and navigate to the directory I want.

**Comment by kevinhwang91** [comment]
I have `set hidden` since I start to use neovim.

But I can't reproduce your issue, maybe mini.vim you provided is fake. 

Check out whether the other file manager plugin wiped the buffer.

**Comment by Hunter522** [comment]
You're right, I moved my `~/.local/share/nvim` (I use paq-nvim) dir somewhere else, reinstalled `vim-plug`, launched neovim, ran `PlugInstall`, restarted neovim with the above `mini.vim` and it seems to work. Essentially clean neovim + vim-plug install. Must have been something weird lingering behind like using another plugin even though I was using the `-u mini.vim` cmd line arg.

**Comment by kevinhwang91** [comment]
Please update the repo, I add double-check bufnr, will be silent now, but not sure whether work as expected.

**Comment by HeWenJin** [comment]
I have the same issue, and after a couple hour of research I find out this problem is related to netrw, add this to init.lua solved my problem
`
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1
`
just some variable to disable netrw, hope it work for you guys
