### ISSUE TITLE
Packer install don't work

### ISSUE THREAD

**Issue by p1k0pan** [kevinhwang91/rnvimr#92]
- `nvim --version`: 0.5
- Operating system/version: arch
- `nvim +'checkhealth rnvimr'`: not found

I used packer to install this plugin, it shows install successful, I can also see it is installed in packer folder. But `checkhealth rnvimr` said no found this plugin and I cann't run ```RnvimrToggle```

![DeepinScreenshot_select-area_20210831153448](https://user-images.githubusercontent.com/36180022/131463986-16a09909-b9f3-4dee-98d5-340a5770ad1d.png)
![DeepinScreenshot_select-area_20210831154906](https://user-images.githubusercontent.com/36180022/131464210-36979e08-308c-47ce-ba04-fcf93ca291ac.png)

**Comment by kevinhwang91** [comment]
Change rnvimr from `opt` to `start`

**Comment by p1k0pan** [comment]
Perfect! Thanks for your time
