### ISSUE TITLE
Feature request: preview images with kitty terminal emulator instead of ueberzug

### ISSUE THREAD

**Issue by Leifrstein** [kevinhwang91/rnvimr#93]
Ranger's able to preview images with kitty (it's one of its features) by adding the following to its conf:
`set preview_images true`
`set preview_images_method kitty`

It'd be great if we could use kitty to preview images instead of ueberzug on your plugin. Also, it'd enable MacOS and BSD users to have image preview on their system too, if they decide to use kitty as their terminal emulator.

**Comment by kevinhwang91** [comment]
No, we can't because kitty uses its protocol to display images. 
Kitty with tmux also can't display image and throw this error msg `ERRO Notification: kitty previews only work in kitty and outside tmux. Make sure your TERM contains the string "kitty"`
