### ISSUE TITLE
rnvimr cannot find the conda python path

### ISSUE THREAD

**Issue by lsli0116** [kevinhwang91/rnvimr#96]
I use the rnvimr in macOS, but sometimes the rnvimr cannot find the condo python3 path and use the python2 of macOS system, I check the health in nvim, and the following is the problem:

> 
> health#rnvimr#check
> ========================================================================
> ## OS
>   - OK: Name: Mac
> 
> ## Ranger
>   - OK: Version: ranger 1.9.3
> 
> ## Python
>   - ERROR: Version: 2.7.18 (default, Oct  2 2021, 04:20:39) [GCC Apple LLVM 13.0.0 (clang-1300.0.29.1) [+internal-os, ptrauth-isa=deploymen
>     - ADVICE:
>       - Python version inside Ranger must be greater than 3
>       - Please install Ranger properly
> 
> ## Pynvim
>   - ERROR: Pynvim is not found in Python Lib
> 
> ## Ueberzug (optional)
>   - INFO: Ueberzug is not support for Mac
> 
> ## RPC
>   - ERROR: RPC: timeout 3s
> 
> health#coc#check
> ========================================================================
>   - OK: Environment check passed
> 
>   - OK: Javascript bundle build/index.js found
>   - OK: Service started
> 
> health#nvim#check
> ========================================================================
> ## Configuration
>   - OK: no issues found
> 
> ## Performance
>   - OK: Build type: Release
> 
> ## Remote Plugins
>   - OK: Up to date
> 
> ## terminal
>   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
>   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
>   - INFO: $TERM_PROGRAM='iTerm.app'
>   - INFO: $COLORTERM='truecolor'
> 
> health#provider#check
> ========================================================================
> ## Clipboard (optional)
>   - OK: Clipboard tool found: pbcopy
> 
> ## Python 2 provider (optional)
>   - INFO: Using: g:python_host_prog = "/usr/bin/python2"
>   - INFO: Executable: /usr/bin/python2
>   - ERROR: Command error (job=29, exit code 1): `'/usr/bin/python2' -c 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; print(neovim.__file__)'` (in '/Users/lsli/.config/nvim')
>     stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
>   - INFO: Python version: 2.7.18
>   - INFO: pynvim version: unable to load neovim Python module
>   - ERROR: pynvim is not installed.
>     Error: unable to load neovim Python module
>     - ADVICE:
>       - Run in shell: /usr/bin/python2 -m pip install pynvim
> 
> ## Python 3 provider (optional)
>   - INFO: Using: g:python3_host_prog = "/Users/lsli/anaconda3/bin/python"
>   - INFO: Executable: /Users/lsli/anaconda3/bin/python
>   - INFO: Python version: 3.7.9
>   - INFO: pynvim version: 0.4.3
>   - OK: Latest pynvim is installed.
> 
> ## Python virtualenv
>   - OK: no $VIRTUAL_ENV
> 
> ## Ruby provider (optional)
>   - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
>   - WARNING: `neovim-ruby-host` not found.
>     - ADVICE:
>       - Run `gem install neovim` to ensure the neovim RubyGem is installed.
>       - Run `gem environment` to ensure the gem bin directory is in $PATH.
>       - If you are using rvm/rbenv/chruby, try "rehashing".
>       - See :help |g:ruby_host_prog| for non-standard gem installations.
> 
> ## Node.js provider (optional)
>   - INFO: Node.js: v16.3.0
>   - INFO: Nvim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
>   - OK: Latest "neovim" npm/yarn package is installed: 4.10.0
> 
> ## Perl provider (optional)
>   - ERROR: perl provider error:
>     - ADVICE:
>       - "Neovim::Ext" cpan module is not installed
> 
> health#treesitter#check
> ========================================================================
> ## Checking treesitter configuration
>   - INFO: Runtime ABI version : 13
>   - OK: Loaded parser for c: ABI version 13

So, I'd like to know how to set the python path for rnvimr. Thanks for advance!

**Comment by kevinhwang91** [comment]
# ArchLinux install all requirements is extremely convenient
yay -S ranger python-pynvim ueberzug

# pip

# macOS users please install ranger by `pip3 ranger-fm` instead of `brew install ranger`
# There're some issues about installation, such as https://github.com/ranger/ranger/issues/1214
# Please refer to the issues of ranger for more details
pip3 install ranger-fm pynvim

# ueberzug is not supported in macOS because it depends on X11
pip3 install ueberzug

**Comment by lsli0116** [comment]
> 

Thanks for your answer, it really helps.
