### ISSUE TITLE
Option to make ranger a buffer (like nerdtree) instead of floating window?

### ISSUE THREAD

**Issue by hamensman** [kevinhwang91/rnvimr#97]
I have a question. Is it possible for the ranger popup to be a buffer, mimicking the likes of nerdtree, instead of a floating window? So it would be a nerdtree, but fully integrated with my ranger config/keybindings (which makes this plugin really stand out).

Just to make it visually clear what I am talking about, take a look at this:
![ranger](https://user-images.githubusercontent.com/76445071/147411325-f73da02e-964f-4881-b25c-49d308cd9204.png)
Pretend these two windows (of ranger and neovim) are one single window, but different buffers. That's pretty much what I mean.

**Comment by kevinhwang91** [comment]
The short answer is `No`. You can use the custom layout to make the floating window more like nerdtree, but I don't suggest this idea.
