### ISSUE TITLE
Empty files opened in ranger term rather than neovim buffers

### ISSUE THREAD

**Issue by glyh** [kevinhwang91/rnvimr#99]
- `nvim --version`:
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
```
- Operating system/version:
```
Linux arch 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
```
- `nvim +'checkhealth rnvimr'`: 
```
rnvimr: health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - WARNING: Ueberzug is not found in Python Lib

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"


```
**Describe the bug**
1. use the following init.lua:
```lua
require('packer').startup({function(use)

  use 'wbthomason/packer.nvim'

  use 'kevinhwang91/rnvimr'

end})
```
2. use the following [rifle.conf](https://gist.github.com/glyh/cdc82419ba6c9021d0819b4e2e1f38bb) in `~/.config/ranger`.
The difference between this one and the default one is that I change the line to fix the issue
```
label open, has xdg-open = xdg-open -- "$@"
```
to
```
label open, has xdg-open = xdg-open "$@"
```
3. Run `xdg-mime default nvim.desktop inode/x-empty` to use neovim to open empty files
4. Start neovim, open ranger in neovim, use touch to create some empty file. 
5. Open that empty file

**Expected behavior**
The file is opened in neovim.

**Screenshots**

![image](https://user-images.githubusercontent.com/12870742/147894943-0af8f20a-13ef-4798-bb70-bf748d29d8ec.png)

**Comment by kevinhwang91** [comment]
Make  sure `label editor, !mime ^text, !ext filetypes  = ${VISUAL:-$EDITOR} -- "$@"
label pager,  !mime ^text, !ext filetypes  = $PAGER -- "$@"
`  have a higher priority than `label open, has xdg-open`

**Comment by glyh** [comment]
@kevinhwang91 This won't fix. The empty file you create should not have any suffix, for exmaple `abcdefg`. Thus this can only be catch up by xdg-open, but in this case I want to edit it in neovim.

**Comment by kevinhwang91** [comment]
Can't understand what you mean. 
Rnvimr only monkey patch `${VISUAL:-$EDITOR} ` candidate for Ranger but keep others' order.

Press `r` in Ranger will show you the candidates of item you selected.

**Comment by glyh** [comment]
Ok, I got it, thanks for your patience.
